import fs from "fs";
import path from "path";
import crypto from "crypto";
import { fileURLToPath } from "url";
import { createInterface } from "readline/promises";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Global error handlers
process.on("unhandledRejection", (err) => {
  console.error("[KERNEL] Unhandled rejection:", err?.message || err);
  if (err?.stack) console.error(err.stack);
});
process.on("uncaughtException", (err) => {
  console.error("[KERNEL] Uncaught exception:", err?.message || err);
  if (err?.stack) console.error(err.stack);
  process.exit(1);
});
const envPath = path.resolve(__dirname, "../.env");

const REQUIRED_KEYS = ["MONGODB_URI", "JWT_SECRET", "PORT", "LAND_DOMAIN"];

const DEFAULTS = {
  LAND_DOMAIN: "localhost",
  LAND_NAME: "My Land",
  PORT: "3000",
  MONGODB_URI: "mongodb://localhost:27017/tree",
  LAND_DEFAULT_TIER: "god",
  REQUIRE_EMAIL: "true",
  ENABLE_FRONTEND_HTML: "true",
  DIRECTORY_URL: "https://dir.treeos.ai",
};

function parseEnv(content) {
  const env = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (val) env[key] = val;
  }
  return env;
}

function buildEnvFile(values) {
  const domain = values.LAND_DOMAIN;
  const port = values.PORT;
  const isLocal = domain === "localhost" || domain.startsWith("localhost") || domain.startsWith("127.") || domain.startsWith("192.168.") || domain.startsWith("10.") || domain.endsWith(".lan") || domain.endsWith(".local") || !domain.includes(".");
  const protocol = isLocal ? "http" : "https";
  const portSuffix = (port !== "80" && port !== "443") ? `:${port}` : "";
  const landUrl = `${protocol}://${domain}${portSuffix}`;

  return `# Tree Land Node Configuration
# Generated by TreeOS first-run setup
# Runtime settings (LAND_NAME, LAND_DEFAULT_TIER, etc.) are stored in the
# .config system node after first boot. Manage them with: treeos config

# Boot-critical
LAND_DOMAIN=${domain}
PORT=${port}
MONGODB_URI=${values.MONGODB_URI}
JWT_SECRET=${values.JWT_SECRET}
CUSTOM_LLM_API_SECRET_KEY=${values.CUSTOM_LLM_API_SECRET_KEY}

# Seeded into .config node on first boot, then managed there
LAND_NAME=${values.LAND_NAME}
LAND_DEFAULT_TIER=${values.LAND_DEFAULT_TIER}
REQUIRE_EMAIL=${values.REQUIRE_EMAIL}
ENABLE_FRONTEND_HTML=${values.ENABLE_FRONTEND_HTML}
DIRECTORY_URL=${values.DIRECTORY_URL}

# Vite (site/ build)
VITE_LAND_URL=${landUrl}
VITE_LAND_NAME=${values.LAND_NAME}
VITE_TREE_API_URL=${landUrl}/api/v1
`;
}

async function interactiveSetup(existingEnv = {}) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log("\n  Welcome to TreeOS.\n");
  console.log("  First-run setup. Answer a few questions to configure your Land.\n");

  const ask = async (label, key) => {
    const def = existingEnv[key] || DEFAULTS[key] || "";
    const hint = def ? ` (${def})` : "";
    const answer = await rl.question(`  ${label}${hint}: `);
    return answer.trim() || def;
  };

  const values = {};
  values.LAND_DOMAIN = (await ask("Domain", "LAND_DOMAIN")).replace(/^https?:\/\//, "").replace(/:\d+$/, "").replace(/\/+$/, "");
  values.LAND_NAME = await ask("Land name", "LAND_NAME");
  values.PORT = await ask("Port", "PORT");
  values.MONGODB_URI = await ask("MongoDB URI", "MONGODB_URI");
  values.JWT_SECRET =
    existingEnv.JWT_SECRET || crypto.randomBytes(32).toString("hex");
  values.CUSTOM_LLM_API_SECRET_KEY =
    existingEnv.CUSTOM_LLM_API_SECRET_KEY ||
    crypto.randomBytes(32).toString("hex");
  values.LAND_DEFAULT_TIER = await ask("Default user tier", "LAND_DEFAULT_TIER");
  values.REQUIRE_EMAIL = await ask("Require email for registration? (true/false)", "REQUIRE_EMAIL");
  values.ENABLE_FRONTEND_HTML =
    existingEnv.ENABLE_FRONTEND_HTML || DEFAULTS.ENABLE_FRONTEND_HTML;
  values.DIRECTORY_URL = await ask("Directory URL (empty for standalone)", "DIRECTORY_URL");

  rl.close();

  fs.writeFileSync(envPath, buildEnvFile(values), "utf8");
  console.log(`\n  Configuration saved to ${envPath}\n`);

  // Extension picker (first-time only)
  await pickExtensions(values.DIRECTORY_URL);

  console.log("  Starting Land server...\n");
}

async function pickExtensions(directoryUrl) {
  if (!directoryUrl) return;

  let extensions;
  try {
    const fetch = (await import("node-fetch")).default;
    console.log(`  Checking extension registry at ${directoryUrl}...`);
    const res = await fetch(`${directoryUrl}/extensions`, {
      headers: { "Content-Type": "application/json" },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    extensions = data.extensions || [];
  } catch (err) {
    console.log(`  Could not reach registry: ${err.message}`);
    console.log("  You can install extensions later with the CLI: treeos ext install <name>\n");
    return;
  }

  if (extensions.length === 0) {
    console.log("  No extensions in registry.\n");
    return;
  }

  const rl = (await import("readline/promises")).createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log(`\n  ${extensions.length} extensions available.\n`);
  const mode = await rl.question("  Install all extensions (a), recommended only (r), or choose individually (c)? (a/r/c): ");
  const installMode = mode.trim().toLowerCase();

  if (installMode === "a") {
    // Install everything
    console.log(`\n  Installing all ${extensions.length} extensions...\n`);
    rl.close();
    const selected = extensions;
    // Jump to install (reuse code below)
    return await installSelected(selected, directoryUrl);
  }

  // Categorize extensions
  const REQUIRED = ["tree-orchestrator"];
  const CORE_AI = ["understanding", "dreams", "raw-ideas"];
  const DATA = ["values", "schedules", "prestige", "transactions", "energy", "billing"];
  const TOOLS = ["scripts", "solana", "gateway", "api-keys", "user-llm"];
  const CONTENT = ["blog", "book", "email", "html-rendering"];
  const SYSTEM = ["user-queries", "deleted-revive", "console"];

  const extMap = {};
  for (const ext of extensions) extMap[ext.name] = ext;

  if (installMode === "r") {
    const recommended = [...REQUIRED, ...CORE_AI, ...SYSTEM].filter(n => extMap[n]);
    console.log(`\n  Installing ${recommended.length} recommended extensions...\n`);
    for (const name of recommended) console.log(`    ${name}`);
    rl.close();
    return await installSelected(recommended.map(n => extMap[n]), directoryUrl);
  }

  const categories = [
    { title: "Required (chat/place/query need this)", names: REQUIRED, defaultYes: true, force: true },
    { title: "AI Intelligence (recommended)", names: CORE_AI, defaultYes: true },
    { title: "Data and Tracking", names: DATA, defaultYes: false },
    { title: "Tools and Integrations", names: TOOLS, defaultYes: false },
    { title: "Content and Rendering", names: CONTENT, defaultYes: false },
    { title: "System Utilities", names: SYSTEM, defaultYes: true },
  ];

  const selected = [];

  for (const cat of categories) {
    const available = cat.names.filter(n => extMap[n]);
    if (!available.length) continue;

    console.log(`\n  ${cat.title}:`);

    if (cat.force) {
      for (const name of available) {
        console.log(`    ${name} v${extMap[name].version} (auto-installed)`);
        selected.push(extMap[name]);
      }
      continue;
    }

    for (const name of available) {
      const ext = extMap[name];
      const hint = cat.defaultYes ? "(Y/n)" : "(y/N)";
      const answer = await rl.question(
        `    ${name} v${ext.version} . ${ext.description || ""} ${hint}: `
      );
      const yes = cat.defaultYes
        ? (!answer.trim() || answer.toLowerCase().startsWith("y"))
        : (answer.toLowerCase().startsWith("y"));
      if (yes) selected.push(ext);
    }
  }

  // Catch any extensions not in categories
  const categorized = new Set([...REQUIRED, ...CORE_AI, ...DATA, ...TOOLS, ...CONTENT, ...SYSTEM]);
  const uncategorized = extensions.filter(e => !categorized.has(e.name));
  if (uncategorized.length) {
    console.log(`\n  Other:`);
    for (const ext of uncategorized) {
      const answer = await rl.question(
        `    ${ext.name} v${ext.version} . ${ext.description || ""} (y/N): `
      );
      if (answer.toLowerCase().startsWith("y")) selected.push(ext);
    }
  }

  rl.close();

  if (selected.length === 0) {
    console.log("\n  No extensions selected. Install later with: treeos ext install <name>\n");
    return;
  }

  await installSelected(selected, directoryUrl);
}

async function installSelected(selected, directoryUrl) {
  console.log(`\n  Installing ${selected.length} extensions...\n`);

  const fetch = (await import("node-fetch")).default;
  const extDir = path.join(__dirname, "extensions");

  for (const ext of selected) {
    try {
      const res = await fetch(`${directoryUrl}/extensions/${ext.name}/${ext.version}`, {
        headers: { "Content-Type": "application/json" },
      });
      if (!res.ok) { console.log(`    ${ext.name}: skipped (HTTP ${res.status})`); continue; }

      const data = await res.json();
      if (!data.files || !data.files.length) { console.log(`    ${ext.name}: skipped (no files)`); continue; }

      const targetDir = path.join(extDir, ext.name);
      if (!fs.existsSync(targetDir)) fs.mkdirSync(targetDir, { recursive: true });

      for (const file of data.files) {
        const normalized = path.normalize(file.path);
        if (normalized.startsWith("..") || path.isAbsolute(normalized)) continue;
        const filePath = path.join(targetDir, normalized);
        const fileDir = path.dirname(filePath);
        if (!fs.existsSync(fileDir)) fs.mkdirSync(fileDir, { recursive: true });
        fs.writeFileSync(filePath, file.content, "utf8");
      }

      console.log(`    ${ext.name} v${ext.version} (${data.files.length} files)`);
    } catch (err) {
      console.log(`    ${ext.name}: failed (${err.message})`);
    }
  }

  console.log();
}

async function boot() {
  let existingEnv = {};

  if (fs.existsSync(envPath)) {
    existingEnv = parseEnv(fs.readFileSync(envPath, "utf8"));
    const missing = REQUIRED_KEYS.filter((k) => !existingEnv[k]);

    if (missing.length === 0) {
      // All good, boot normally
      await import("./server.js");
      return;
    }

    console.log(
      `\n  Missing required config: ${missing.join(", ")}`
    );
    await interactiveSetup(existingEnv);
  } else {
    await interactiveSetup();
  }

  // Reload env and boot
  await import("./server.js");
}

boot().catch((err) => {
  console.error("Boot failed:", err);
  process.exit(1);
});
