#!/usr/bin/env node
// TreeOS Land — boot wizard.
//
// First-run setup: collect the boot-critical env (LAND_DOMAIN, PORT,
// MONGODB_URI, JWT_SECRET), write .env, discover the extensions on
// disk, and hand control to server.js.
//
// Subsequent boots short-circuit straight to server.js when .env
// looks complete. `node boot.js --setup` re-runs the extension
// picker without touching the env.

import fs from "fs";
import path from "path";
import crypto from "crypto";
import { fileURLToPath } from "url";
import { createInterface } from "readline/promises";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath   = path.resolve(__dirname, ".env");

// ────────────────────────────────────────────────────────────────────
// Preflight
// ────────────────────────────────────────────────────────────────────

if (!fs.existsSync(path.join(__dirname, "node_modules"))) {
  console.error("\n  Dependencies not installed. Run:\n\n    npm install\n\n  Then try again.\n");
  process.exit(1);
}

process.on("unhandledRejection", (err) => {
  console.error("[KERNEL] Unhandled rejection:", err?.message || err);
  if (err?.stack) console.error(err.stack);
});
process.on("uncaughtException", (err) => {
  console.error("[KERNEL] Uncaught exception:", err?.message || err);
  if (err?.stack) console.error(err.stack);
  process.exit(1);
});

// ────────────────────────────────────────────────────────────────────
// Env shape
// ────────────────────────────────────────────────────────────────────

const REQUIRED_KEYS = ["MONGODB_URI", "JWT_SECRET", "PORT", "LAND_DOMAIN"];

const DEFAULTS = {
  LAND_DOMAIN: "localhost",
  LAND_NAME:   "My Land",
  PORT:        "3000",
  MONGODB_URI: "mongodb://localhost:27017/land",
};

function parseEnv(content) {
  const env = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const val = trimmed.slice(eq + 1).trim();
    if (val) env[key] = val;
  }
  return env;
}

function buildEnvFile(values) {
  const domain = values.LAND_DOMAIN;
  const port   = values.PORT;
  const isLocal =
    domain === "localhost"          ||
    domain.startsWith("localhost")  ||
    domain.startsWith("127.")       ||
    domain.startsWith("192.168.")   ||
    domain.startsWith("10.")        ||
    domain.endsWith(".lan")         ||
    domain.endsWith(".local")       ||
    !domain.includes(".");
  const protocol   = isLocal ? "http" : "https";
  const portSuffix = (port !== "80" && port !== "443") ? `:${port}` : "";
  const landUrl    = `${protocol}://${domain}${portSuffix}`;

  return `# TreeOS Land config — generated by first-run setup.
# Runtime settings (extension toggles, llm timeouts, …) are stored in
# the .config seed space after first boot. Manage them with:
#   ibp:do <land>  { action: "set-config",    args: { key, value } }
#   ibp:do <land>  { action: "delete-config", args: { key } }

# Boot-critical
LAND_DOMAIN=${domain}
PORT=${port}
MONGODB_URI=${values.MONGODB_URI}
JWT_SECRET=${values.JWT_SECRET}
CUSTOM_LLM_API_SECRET_KEY=${values.CUSTOM_LLM_API_SECRET_KEY}

# Seeded into .config on first boot
LAND_NAME=${values.LAND_NAME}

# Site/frontend build hints (read by Vite if you build the React site)
VITE_LAND_URL=${landUrl}
VITE_LAND_NAME=${values.LAND_NAME}
`;
}

// ────────────────────────────────────────────────────────────────────
// Setup flow
// ────────────────────────────────────────────────────────────────────

async function interactiveSetup(existingEnv = {}) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log("\n  Welcome to TreeOS.");
  console.log("  First-run setup. A few questions to configure your land.\n");

  const ask = async (label, key) => {
    const def  = existingEnv[key] || DEFAULTS[key] || "";
    const hint = def ? ` (${def})` : "";
    const ans  = await rl.question(`  ${label}${hint}: `);
    return ans.trim() || def;
  };

  const quickAns = await rl.question("  Quick setup for localhost? (Y/n): ");
  const quick = !quickAns.trim() || quickAns.toLowerCase().startsWith("y");

  const values = {};
  if (quick) {
    values.LAND_DOMAIN = "localhost";
    values.LAND_NAME   = await ask("Land name", "LAND_NAME");
    values.PORT        = "3000";
    values.MONGODB_URI = DEFAULTS.MONGODB_URI;
    console.log("\n  Localhost defaults: port 3000, MongoDB localhost:27017/land.\n");
  } else {
    values.LAND_DOMAIN = (await ask("Domain", "LAND_DOMAIN"))
      .replace(/^https?:\/\//, "").replace(/:\d+$/, "").replace(/\/+$/, "");
    values.LAND_NAME   = await ask("Land name",   "LAND_NAME");
    values.PORT        = await ask("Port",        "PORT");
    values.MONGODB_URI = await ask("MongoDB URI", "MONGODB_URI");
  }

  values.JWT_SECRET                = existingEnv.JWT_SECRET                || crypto.randomBytes(32).toString("hex");
  values.CUSTOM_LLM_API_SECRET_KEY = existingEnv.CUSTOM_LLM_API_SECRET_KEY || crypto.randomBytes(32).toString("hex");

  rl.close();

  fs.writeFileSync(envPath, buildEnvFile(values), "utf8");
  console.log(`\n  Configuration saved to ${envPath}\n`);

  await pickExtensions();

  console.log("  Starting Land server...\n");
}

// ────────────────────────────────────────────────────────────────────
// Extension picker
// ────────────────────────────────────────────────────────────────────
//
// Scans extensions/ for directories with a manifest.js, presents a
// terse list, lets the operator enable all or pick individually. The
// loader reads `.treeos-profile` to know which extensions to load on
// boot. Extensions not listed in the profile stay on disk but
// dormant.

async function discoverLocalExtensions() {
  const extDir = path.join(__dirname, "extensions");
  if (!fs.existsSync(extDir)) return [];

  const out = [];
  for (const entry of fs.readdirSync(extDir, { withFileTypes: true })) {
    if (!entry.isDirectory())       continue;
    if (entry.name.startsWith("_")) continue;   // _template / _code-strategy-template
    if (entry.name.startsWith(".")) continue;
    const manifestPath = path.join(extDir, entry.name, "manifest.js");
    if (!fs.existsSync(manifestPath)) continue;
    try {
      const { pathToFileURL } = await import("url");
      const { default: manifest } = await import(pathToFileURL(manifestPath).href);
      out.push({
        name:        manifest.name        || entry.name,
        version:     manifest.version     || "0.0.0",
        description: manifest.description || "",
      });
    } catch (err) {
      console.log(`    (skipped ${entry.name}: ${err.message})`);
    }
  }
  return out;
}

async function pickExtensions() {
  const extensions = await discoverLocalExtensions();
  if (extensions.length === 0) {
    console.log("  No extensions found on disk. Boot will run kernel-only.\n");
    return;
  }

  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log(`  ${extensions.length} extensions on disk:\n`);
  for (const ext of extensions) {
    const desc = ext.description ? ` — ${ext.description}` : "";
    console.log(`    ${ext.name}  v${ext.version}${desc}`);
  }

  console.log();
  const ans = (await rl.question("  Enable all? (Y/n, or 'p' to pick individually): ")).trim().toLowerCase();

  let selected;
  if (ans === "p" || ans === "pick") {
    selected = [];
    for (const ext of extensions) {
      const yn = (await rl.question(`    ${ext.name} (y/N): `)).trim().toLowerCase();
      if (yn.startsWith("y")) selected.push(ext);
    }
  } else if (ans === "n" || ans === "no") {
    selected = [];
  } else {
    selected = extensions;
  }

  rl.close();

  const profilePath = path.join(__dirname, "extensions", ".treeos-profile");
  if (selected.length === 0) {
    if (fs.existsSync(profilePath)) fs.unlinkSync(profilePath);
    console.log("\n  Profile cleared. Boot will run kernel-only.\n");
    return;
  }

  fs.writeFileSync(profilePath, selected.map(e => e.name).join("\n") + "\n", "utf8");
  console.log(`\n  Profile saved. ${selected.length} extensions will load on boot.\n`);
}

// ────────────────────────────────────────────────────────────────────
// Entry
// ────────────────────────────────────────────────────────────────────

async function loadEnvIntoProcess() {
  if (!fs.existsSync(envPath)) return {};
  const env = parseEnv(fs.readFileSync(envPath, "utf8"));
  for (const [key, value] of Object.entries(env)) {
    if (!process.env[key]) process.env[key] = value;
  }
  return env;
}

async function boot() {
  // --setup: re-run the extension picker without touching .env.
  if (process.argv.includes("--setup")) {
    await loadEnvIntoProcess();
    await pickExtensions();
    console.log("  Done. Restart the server to apply.\n");
    process.exit(0);
  }

  let env = {};
  if (fs.existsSync(envPath)) {
    env = parseEnv(fs.readFileSync(envPath, "utf8"));
    const missing = REQUIRED_KEYS.filter((k) => !env[k]);
    if (missing.length === 0) {
      // Happy path: env is complete. Load it and start the server.
      for (const [key, value] of Object.entries(env)) {
        if (!process.env[key]) process.env[key] = value;
      }
      await import("./server.js");
      return;
    }
    console.log(`\n  Missing required config: ${missing.join(", ")}`);
  }

  // First boot OR env is incomplete: run the wizard, then launch.
  await interactiveSetup(env);
  await loadEnvIntoProcess();
  await import("./server.js");
}

boot();
