import fs from "fs";
import path from "path";
import crypto from "crypto";
import { fileURLToPath } from "url";
import { createInterface } from "readline/promises";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.resolve(__dirname, "../.env");

const REQUIRED_KEYS = ["MONGODB_URI", "JWT_SECRET", "PORT", "LAND_DOMAIN"];

const DEFAULTS = {
  LAND_DOMAIN: "localhost",
  LAND_NAME: "My Land",
  PORT: "3000",
  MONGODB_URI: "mongodb://localhost:27017/tree",
  LAND_DEFAULT_TIER: "god",
  REQUIRE_EMAIL: "true",
  ENABLE_FRONTEND_HTML: "true",
  DIRECTORY_URL: "https://dir.treeos.ai",
};

function parseEnv(content) {
  const env = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (val) env[key] = val;
  }
  return env;
}

function buildEnvFile(values) {
  const domain = values.LAND_DOMAIN;
  const port = values.PORT;
  const isLocal = domain === "localhost" || domain.startsWith("localhost") || domain.startsWith("127.") || domain.startsWith("192.168.") || domain.startsWith("10.");
  const protocol = isLocal ? "http" : "https";
  const portSuffix = (port !== "80" && port !== "443") ? `:${port}` : "";
  const landUrl = `${protocol}://${domain}${portSuffix}`;

  return `# Tree Land Node Configuration
# Generated by TreeOS first-run setup
# Runtime settings (LAND_NAME, LAND_DEFAULT_TIER, etc.) are stored in the
# .config system node after first boot. Manage them with: treeos config

# Boot-critical
LAND_DOMAIN=${domain}
PORT=${port}
MONGODB_URI=${values.MONGODB_URI}
JWT_SECRET=${values.JWT_SECRET}
CUSTOM_LLM_API_SECRET_KEY=${values.CUSTOM_LLM_API_SECRET_KEY}

# Seeded into .config node on first boot, then managed there
LAND_NAME=${values.LAND_NAME}
LAND_DEFAULT_TIER=${values.LAND_DEFAULT_TIER}
REQUIRE_EMAIL=${values.REQUIRE_EMAIL}
ENABLE_FRONTEND_HTML=${values.ENABLE_FRONTEND_HTML}
DIRECTORY_URL=${values.DIRECTORY_URL}

# Vite (site/ build)
VITE_LAND_URL=${landUrl}
VITE_TREE_API_URL=${landUrl}/api/v1
`;
}

async function interactiveSetup(existingEnv = {}) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log("\n  Welcome to TreeOS.\n");
  console.log("  First-run setup. Answer a few questions to configure your Land.\n");

  const ask = async (label, key) => {
    const def = existingEnv[key] || DEFAULTS[key] || "";
    const hint = def ? ` (${def})` : "";
    const answer = await rl.question(`  ${label}${hint}: `);
    return answer.trim() || def;
  };

  const values = {};
  values.LAND_DOMAIN = await ask("Domain", "LAND_DOMAIN");
  values.LAND_NAME = await ask("Land name", "LAND_NAME");
  values.PORT = await ask("Port", "PORT");
  values.MONGODB_URI = await ask("MongoDB URI", "MONGODB_URI");
  values.JWT_SECRET =
    existingEnv.JWT_SECRET || crypto.randomBytes(32).toString("hex");
  values.CUSTOM_LLM_API_SECRET_KEY =
    existingEnv.CUSTOM_LLM_API_SECRET_KEY ||
    crypto.randomBytes(32).toString("hex");
  values.LAND_DEFAULT_TIER = await ask("Default user tier", "LAND_DEFAULT_TIER");
  values.REQUIRE_EMAIL = await ask("Require email for registration? (true/false)", "REQUIRE_EMAIL");
  values.ENABLE_FRONTEND_HTML =
    existingEnv.ENABLE_FRONTEND_HTML || DEFAULTS.ENABLE_FRONTEND_HTML;
  values.DIRECTORY_URL = await ask("Directory URL (empty for standalone)", "DIRECTORY_URL");

  rl.close();

  fs.writeFileSync(envPath, buildEnvFile(values), "utf8");
  console.log(`\n  Configuration saved to ${envPath}\n`);
  console.log("  Starting Land server...\n");
}

async function boot() {
  let existingEnv = {};

  if (fs.existsSync(envPath)) {
    existingEnv = parseEnv(fs.readFileSync(envPath, "utf8"));
    const missing = REQUIRED_KEYS.filter((k) => !existingEnv[k]);

    if (missing.length === 0) {
      // All good, boot normally
      await import("./server.js");
      return;
    }

    console.log(
      `\n  Missing required config: ${missing.join(", ")}`
    );
    await interactiveSetup(existingEnv);
  } else {
    await interactiveSetup();
  }

  // Reload env and boot
  await import("./server.js");
}

boot().catch((err) => {
  console.error("Boot failed:", err);
  process.exit(1);
});
