#!/usr/bin/env node
// Land setup wizard. Run once before first boot.
// Usage: node land/setup.js

import readline from "readline";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.resolve(__dirname, "../.env");

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

function ask(question, defaultVal) {
  const def = defaultVal ? ` (${defaultVal})` : "";
  return new Promise((resolve) => {
    rl.question(`  ${question}${def}: `, (answer) => {
      resolve(answer.trim() || defaultVal || "");
    });
  });
}

function askYN(question, defaultVal = true) {
  const hint = defaultVal ? "(Y/n)" : "(y/N)";
  return new Promise((resolve) => {
    rl.question(`  ${question} ${hint}: `, (answer) => {
      if (!answer.trim()) return resolve(defaultVal);
      resolve(answer.toLowerCase().startsWith("y"));
    });
  });
}

async function fetchJSON(url) {
  const fetch = (await import("node-fetch")).default;
  const res = await fetch(url, { headers: { "Content-Type": "application/json" } });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json();
}

console.log(`
  TreeOS Land Setup
  ─────────────────────────────

  This will configure your land and install extensions.
`);

async function run() {
  // ── Step 1: Basic config ──
  console.log("  1. Land Configuration\n");

  const existing = {};
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, "utf8");
    for (const line of content.split("\n")) {
      const match = line.match(/^([A-Z_]+)=(.*)$/);
      if (match) existing[match[1]] = match[2];
    }
  }

  const domain = await ask("Domain", existing.LAND_DOMAIN || "localhost");
  const landName = await ask("Land name", existing.LAND_NAME || "My Land");
  const port = await ask("Port", existing.PORT || "80");
  const mongoUri = await ask("MongoDB URI", existing.MONGODB_URI || "mongodb://localhost:27017/treeos");
  const directoryUrl = await ask("Directory URL", existing.DIRECTORY_URL || "https://dir.treeos.ai");

  // ── Step 2: Extensions ──
  console.log("\n  2. Extensions\n");

  let availableExtensions = [];
  try {
    console.log(`  Fetching extensions from ${directoryUrl}...`);
    const data = await fetchJSON(`${directoryUrl}/extensions`);
    availableExtensions = data.extensions || [];
  } catch (err) {
    console.log(`  Could not reach registry: ${err.message}`);
    console.log("  You can install extensions later with 'treeos ext install <name>'\n");
  }

  const selectedExtensions = [];

  if (availableExtensions.length > 0) {
    console.log(`  ${availableExtensions.length} extensions available:\n`);

    for (let i = 0; i < availableExtensions.length; i++) {
      const ext = availableExtensions[i];
      const install = await askYN(`  [${i + 1}/${availableExtensions.length}] ${ext.name} v${ext.version} . ${ext.description}. Install?`, true);
      if (install) {
        selectedExtensions.push(ext);
      }
    }

    console.log(`\n  Selected: ${selectedExtensions.length} extensions`);
  }

  // ── Step 3: Write .env ──
  console.log("\n  3. Writing configuration\n");

  const envContent = `# TreeOS Land Configuration (generated by setup.js)
PORT=${port}
LAND_DOMAIN=${domain}
LAND_NAME=${landName}
MONGODB_URI=${mongoUri}
DIRECTORY_URL=${directoryUrl}

# Features
ENABLE_FRONTEND_HTML=true
`;

  fs.writeFileSync(envPath, envContent, "utf8");
  console.log(`  Wrote ${envPath}`);

  // ── Step 4: Install selected extensions ──
  if (selectedExtensions.length > 0) {
    console.log(`\n  4. Installing extensions\n`);

    for (const ext of selectedExtensions) {
      try {
        console.log(`  Installing ${ext.name} v${ext.version}...`);
        const fullExt = await fetchJSON(`${directoryUrl}/extensions/${ext.name}/${ext.version}`);

        if (!fullExt.files || !fullExt.files.length) {
          console.log(`    Skipped (no files in registry)`);
          continue;
        }

        const extDir = path.join(__dirname, "extensions", ext.name);
        if (!fs.existsSync(extDir)) {
          fs.mkdirSync(extDir, { recursive: true });
        }

        for (const file of fullExt.files) {
          const normalized = path.normalize(file.path);
          if (normalized.startsWith("..") || path.isAbsolute(normalized)) continue;

          const filePath = path.join(extDir, normalized);
          const fileDir = path.dirname(filePath);
          if (!fs.existsSync(fileDir)) {
            fs.mkdirSync(fileDir, { recursive: true });
          }
          fs.writeFileSync(filePath, file.content, "utf8");
        }

        console.log(`    Installed (${fullExt.files.length} files)`);
      } catch (err) {
        console.log(`    Failed: ${err.message}`);
      }
    }
  }

  // ── Done ──
  console.log(`
  Setup complete.

  Start your land:
    npm start

  Then connect from the CLI:
    treeos connect ${domain === "localhost" ? `http://localhost:${port}` : `https://${domain}`}
    treeos register
`);

  rl.close();
}

run().catch((err) => {
  console.error("Setup failed:", err.message);
  rl.close();
  process.exit(1);
});
