#!/usr/bin/env node

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { execSync } from "child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const BOLD = "\x1b[1m";
const DIM = "\x1b[2m";
const GREEN = "\x1b[32m";
const CYAN = "\x1b[36m";
const YELLOW = "\x1b[33m";
const RED = "\x1b[31m";
const RESET = "\x1b[0m";

const args = process.argv.slice(2);
const projectName = args[0];

if (!projectName || projectName === "--help" || projectName === "-h") {
  console.log(`
${BOLD}create-treeos${RESET}  Scaffold a TreeOS land server.

${BOLD}Usage:${RESET}
  npx create-treeos my-land
  npx create-treeos .          ${DIM}(current directory)${RESET}

${BOLD}What it does:${RESET}
  1. Copies the land server template
  2. Installs dependencies
  3. First boot walks you through configuration

${BOLD}After setup:${RESET}
  cd my-land
  node boot.js

${BOLD}CLI (separate install):${RESET}
  npm install -g treeos
  treeos connect http://localhost:3000
  treeos start

${DIM}https://treeos.ai${RESET}
`);
  process.exit(0);
}

// Resolve target directory
const targetDir = path.resolve(process.cwd(), projectName);
const targetName = path.basename(targetDir);

// Check if directory exists and is not empty
if (projectName !== ".") {
  if (fs.existsSync(targetDir)) {
    const contents = fs.readdirSync(targetDir);
    if (contents.length > 0) {
      console.error(`${RED}Directory "${targetName}" already exists and is not empty.${RESET}`);
      process.exit(1);
    }
  } else {
    fs.mkdirSync(targetDir, { recursive: true });
  }
} else {
  // Current directory. Check if it's empty (allow .git)
  const contents = fs.readdirSync(targetDir).filter(f => f !== ".git" && f !== ".gitignore");
  if (contents.length > 0) {
    console.error(`${RED}Current directory is not empty. Use a new directory name.${RESET}`);
    process.exit(1);
  }
}

console.log(`
${BOLD}${GREEN}TreeOS${RESET}
${DIM}Planting a new land...${RESET}
`);

// Copy template
const templateDir = path.join(__dirname, "template");

if (!fs.existsSync(templateDir)) {
  console.error(`${RED}Template directory not found. Package may be corrupted.${RESET}`);
  process.exit(1);
}

function copyDir(src, dest) {
  if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });

  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.name === "node_modules") continue;
    if (entry.name === ".env") continue; // generated by boot wizard

    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

try {
  copyDir(templateDir, targetDir);
} catch (err) {
  console.error(`${RED}Failed to copy template: ${err.message}${RESET}`);
  process.exit(1);
}

// Write .gitignore if not present
const gitignorePath = path.join(targetDir, ".gitignore");
if (!fs.existsSync(gitignorePath)) {
  fs.writeFileSync(gitignorePath, `node_modules/
.env
.land/
uploads/
*.log
`, "utf8");
}

console.log(`${GREEN}Template copied.${RESET}`);

// Install dependencies
console.log(`${DIM}Installing dependencies...${RESET}`);
try {
  execSync("npm install --production --no-fund --no-audit", {
    cwd: targetDir,
    stdio: "pipe",
    timeout: 120000,
  });
  console.log(`${GREEN}Dependencies installed.${RESET}`);
} catch (err) {
  console.log(`${YELLOW}npm install failed. Run it manually: cd ${targetName} && npm install${RESET}`);
}

// Done
console.log(`
${BOLD}${GREEN}Land scaffolded.${RESET}

${BOLD}Next steps:${RESET}

  ${CYAN}cd ${targetName}${RESET}
  ${CYAN}node boot.js${RESET}          ${DIM}First boot runs the setup wizard${RESET}

${BOLD}Then install the CLI:${RESET}

  ${CYAN}npm install -g treeos${RESET}
  ${CYAN}treeos connect http://localhost:3000${RESET}
  ${CYAN}treeos start${RESET}

${DIM}The seed is planted. Let it grow.${RESET}
`);
