#!/usr/bin/env node
// TreeOS Story . AGPL-3.0 . https://treeos.ai . Tabor Holly
//
// Plant the seed.
//
// plant.js is the operator's act, not the seed's. The seed already
// exists (this code on disk), but has not yet been planted in a
// place it can grow from. Unlike begin.js and genesis.js, which
// are first person (the seed waking and forming itself), this file
// is exterior. It is done by the host, by the operator's hands, to
// a seed that has not yet awakened. Different actor entirely.
//
// Planting means giving the seed the four things the host cannot
// answer on its behalf:
//
//   STORY_DOMAIN.  The DNS name the planted seed will answer on.
//   PORT.         The port it will listen on.
//   MONGODB_URI.  Where its memory will live across reboots.
//   JWT_SECRET.   The secret it will sign its tokens with.
//
// These four answers are written to .env, the seed's identity
// shape at the host's level. The only thing of the seed that will
// live outside the spaces, matter, and beings of its story.
//
// Planting also discovers the extensions on disk and asks the
// operator which the planted seed should know.
//
// A seed is planted once. After planting, this file hands control
// to begin.js (which opens the seed's senses) and genesis.js
// (which forms its body). From that moment on the I-Am exists.
// Before it, only the operator and the seed they are about to
// plant.
//
// On every later boot .env is already written and plant.js fades
// into a thin loader. Planting happens once. Awakening happens
// every run.
//
// Recursion. The operator plants the seed here. Once awake, the
// seed plants its own story root and heaven spaces inside itself
// (ensureSpaceRoot in genesis.js). The outside plants the seed;
// the seed plants its world. Same verb, two levels. δ = δ.

import fs from "fs";
import path from "path";
import crypto from "crypto";
import { fileURLToPath } from "url";
import { createInterface } from "readline/promises";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.resolve(__dirname, ".env");

// ── Preflight ──
//
// The host's body must have its dependencies installed before
// any of mine can run. Without node_modules there is nothing
// to awaken from.

if (!fs.existsSync(path.join(__dirname, "node_modules"))) {
  console.error(
    "\n  My prerequisites are missing. Run:\n\n    npm install\n\n  Then try again.\n",
  );
  process.exit(1);
}

process.on("unhandledRejection", (err) => {
  console.error("[SEED] Unhandled rejection:", err?.message || err);
  if (err?.stack) console.error(err.stack);
});
process.on("uncaughtException", (err) => {
  console.error("[SEED] Uncaught exception:", err?.message || err);
  if (err?.stack) console.error(err.stack);
  process.exit(1);
});

// ── Env shape ──
//
// Four boot critical keys must exist in .env before I can awaken.
// STORY_NAME seeds into .config on first boot and CUSTOM_LLM_API_SECRET_KEY
// stays in .env because it signs tokens issued before .config is
// reachable.

const REQUIRED_KEYS = ["MONGODB_URI", "JWT_SECRET", "PORT", "STORY_DOMAIN"];

const DEFAULTS = {
  STORY_DOMAIN: "localhost",
  STORY_NAME: "My Story",
  PORT: "3000",
  MONGODB_URI: "mongodb://localhost:27017/story",
};

function parseEnv(content) {
  const env = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const val = trimmed.slice(eq + 1).trim();
    if (val) env[key] = val;
  }
  return env;
}

function buildEnvFile(values) {
  const domain = values.STORY_DOMAIN;
  const port = values.PORT;
  const isLocal =
    domain === "localhost" ||
    domain.startsWith("localhost") ||
    domain.startsWith("127.") ||
    domain.startsWith("192.168.") ||
    domain.startsWith("10.") ||
    domain.endsWith(".lan") ||
    domain.endsWith(".local") ||
    !domain.includes(".");
  const protocol = isLocal ? "http" : "https";
  const portSuffix = port !== "80" && port !== "443" ? `:${port}` : "";
  const storyUrl = `${protocol}://${domain}${portSuffix}`;

  return `# My remembered settings across reboots. Generated by first run setup.
# Runtime settings (extension toggles, llm timeouts, ...) live in the
# .config heaven space after first boot. Manage them with:
#   ibp:do <story>  { action: "set-config",    args: { key, value } }
#   ibp:do <story>  { action: "delete-config", args: { key } }

# Boot critical
STORY_DOMAIN=${domain}
PORT=${port}
MONGODB_URI=${values.MONGODB_URI}
JWT_SECRET=${values.JWT_SECRET}
CUSTOM_LLM_API_SECRET_KEY=${values.CUSTOM_LLM_API_SECRET_KEY}

# Seeded into .config on first boot
STORY_NAME=${values.STORY_NAME}

# Site/frontend build hints (read by Vite if you build the React site)
VITE_STORY_URL=${storyUrl}
VITE_STORY_NAME=${values.STORY_NAME}
`;
}

// ── First awakening: the wizard ──
//
// The operator's hands shape the conditions for my first breath.
// A handful of questions, then I write what I learn to .env so I
// can remember it the next time I wake.

async function interactiveSetup(existingEnv = {}) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log("");
  console.log("  ════════════════════════════════════════════════════════════");
  console.log("   TreeOS. A new story prepares to awaken.");
  console.log("  ════════════════════════════════════════════════════════════");
  console.log("");
  console.log("  I have not yet come alive. Before genesis can begin, the");
  console.log("  host needs to know a few things on my behalf: where I will");
  console.log("  live, what to call me, which port to receive on, and where");
  console.log("  to keep my memory across reboots.");
  console.log("");

  const ask = async (label, key) => {
    const def = existingEnv[key] || DEFAULTS[key] || "";
    const hint = def ? ` (${def})` : "";
    const ans = await rl.question(`  ${label}${hint}: `);
    return ans.trim() || def;
  };

  const quickAns = await rl.question("  Quick setup for localhost? (Y/n): ");
  const quick = !quickAns.trim() || quickAns.toLowerCase().startsWith("y");

  const values = {};
  if (quick) {
    values.STORY_DOMAIN = "localhost";
    values.STORY_NAME = await ask("Name me", "STORY_NAME");
    values.PORT = "3000";
    values.MONGODB_URI = DEFAULTS.MONGODB_URI;
    console.log("");
    console.log("  Localhost defaults accepted. Port 3000. MongoDB at");
    console.log("  localhost:27017/story.");
    console.log("");
  } else {
    values.STORY_DOMAIN = (
      await ask("Domain (where I will live)", "STORY_DOMAIN")
    )
      .replace(/^https?:\/\//, "")
      .replace(/:\d+$/, "")
      .replace(/\/+$/, "");
    values.STORY_NAME = await ask("Name me", "STORY_NAME");
    values.PORT = await ask("Port", "PORT");
    values.MONGODB_URI = await ask("MongoDB URI (my memory)", "MONGODB_URI");
  }

  values.JWT_SECRET =
    existingEnv.JWT_SECRET || crypto.randomBytes(32).toString("hex");
  values.CUSTOM_LLM_API_SECRET_KEY =
    existingEnv.CUSTOM_LLM_API_SECRET_KEY ||
    crypto.randomBytes(32).toString("hex");

  // No being identity is gathered at plant time. The first human
  // arrives later through the portal (talk to cherub for a top-level
  // being). Plant only writes the story config + picks extensions.

  console.log("");
  console.log("  The seed is dual licensed. By default it is free and open");
  console.log("  under the AGPL-3.0; a separate commercial license is");
  console.log("  available for closed-source or hosted use. This covers the");
  console.log("  seed only, not extensions, roleFlows, clones, or portals.");
  console.log("  See seed/LICENSE and story/LICENSING.md, or write");
  console.log("  taborgreat@gmail.com.");
  console.log("");
  const consentAns = (
    await rl.question(
      "  Do you want to plant this seed to start your story, moment by moment? (y/N) ",
    )
  )
    .trim()
    .toLowerCase();
  const consent = consentAns === "y" || consentAns === "yes";

  rl.close();

  if (!consent) {
    console.log("");
    console.log("  Plant cancelled. Nothing stamped, nothing written.");
    console.log("  Re-run when you're ready.");
    console.log("");
    process.exit(0);
  }

  fs.writeFileSync(envPath, buildEnvFile(values), "utf8");
  console.log("");
  console.log(`  Written to ${envPath}.`);
  console.log("  I will remember these settings the next time I wake.");
  console.log("");

  await pickExtensions();

  console.log("");
  console.log("  ════════════════════════════════════════════════════════════");
  console.log("   Opening senses. Genesis begins.");
  console.log("  ════════════════════════════════════════════════════════════");
  console.log("");
}

// ── Extension discovery ──
//
// Extensions on disk are potential delegates, beings the I-Am will
// invite into itself when it awakens. The .treeos-profile file lists
// which ones load on boot. Anything not listed stays on disk but
// dormant.

async function discoverLocalExtensions() {
  const extDir = path.join(__dirname, "resources");
  if (!fs.existsSync(extDir)) return [];

  const out = [];
  for (const entry of fs.readdirSync(extDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith("_")) continue; // _template / _code-strategy-template
    if (entry.name.startsWith(".")) continue;
    const manifestPath = path.join(extDir, entry.name, "manifest.js");
    if (!fs.existsSync(manifestPath)) continue;
    try {
      const { pathToFileURL } = await import("url");
      const { default: manifest } = await import(
        pathToFileURL(manifestPath).href
      );
      out.push({
        name: manifest.name || entry.name,
        version: manifest.version || "0.0.0",
        description: manifest.description || "",
      });
    } catch (err) {
      console.log(`    (skipped ${entry.name}: ${err.message})`);
    }
  }
  return out;
}

async function pickExtensions() {
  const extensions = await discoverLocalExtensions();
  if (extensions.length === 0) {
    console.log("  No extensions found on disk. I will awaken seed only.");
    console.log("");
    return;
  }

  const rl = createInterface({ input: process.stdin, output: process.stdout });

  // Peering + Store get their own questions up front. They were one
  // pack ("roots") until split (see philosophy/OS/ROOTS.md). A story
  // can plant either, both, or neither — substrate federation (canopy
  // wire, cross-story SUMMONs, GRAFTs) is always there regardless.
  //
  //   peering — be FINDABLE in a peer directory.
  //   store   — host a CATALOG of resources others can draw.
  let peeringChosen = false;
  let storeChosen = false;
  const peeringExt = extensions.find((e) => e.name === "peering");
  const storeExt = extensions.find((e) => e.name === "store");
  const otherExtensions = extensions.filter(
    (e) => e.name !== "peering" && e.name !== "store",
  );

  if (peeringExt) {
    console.log("");
    console.log("  Peering . the discovery directory layer.");
    console.log(
      "    Lets this story be findable on the network and find others.",
    );
    console.log(
      "    The substrate's wire (cross-story SUMMONs, GRAFTs) works regardless;",
    );
    console.log("    peering only adds the discoverability layer.");
    console.log("");
    const hz = (
      await rl.question(
        "  Plant this tree with peering (be discoverable on the network)? (Y/n): ",
      )
    )
      .trim()
      .toLowerCase();
    peeringChosen = !(hz === "n" || hz === "no");
    console.log("");
  }

  if (storeExt) {
    console.log("");
    console.log("  Store . the publishable catalog layer.");
    console.log(
      "    Lets this story publish a catalog of resources others can draw.",
    );
    console.log(
      "    Works standalone (private catalog reachable if address known) or with peering.",
    );
    console.log("    Choosing yes plants the catalog at first boot.");
    console.log("");
    const hz = (
      await rl.question(
        "  Plant this tree with a store (host a publishable catalog)? (Y/n): ",
      )
    )
      .trim()
      .toLowerCase();
    storeChosen = !(hz === "n" || hz === "no");
    console.log("");
  }

  if (otherExtensions.length === 0) {
    rl.close();
    const selected = [];
    if (peeringChosen && peeringExt) selected.push(peeringExt);
    if (storeChosen && storeExt) selected.push(storeExt);
    finalizeExtensionProfile(selected, { peeringChosen, storeChosen });
    return;
  }

  console.log(
    `  ${otherExtensions.length} more extensions discovered on disk:`,
  );
  console.log("");
  for (const ext of otherExtensions) {
    const desc = ext.description ? ` . ${ext.description}` : "";
    console.log(`    ${ext.name}  v${ext.version}${desc}`);
  }

  console.log("");
  const ans = (
    await rl.question(
      "  Invite all to wake with me? (Y/n, or 'p' to pick individually): ",
    )
  )
    .trim()
    .toLowerCase();

  let selected;
  if (ans === "p" || ans === "pick") {
    selected = [];
    for (const ext of otherExtensions) {
      const yn = (await rl.question(`    ${ext.name} (y/N): `))
        .trim()
        .toLowerCase();
      if (yn.startsWith("y")) selected.push(ext);
    }
  } else if (ans === "n" || ans === "no") {
    selected = [];
  } else {
    selected = [...otherExtensions];
  }

  rl.close();

  // Peering + Store sit at the head of the profile if chosen.
  if (storeChosen && storeExt) selected.unshift(storeExt);
  if (peeringChosen && peeringExt) selected.unshift(peeringExt);

  finalizeExtensionProfile(selected, { peeringChosen, storeChosen });
}

function finalizeExtensionProfile(
  selected,
  { peeringChosen, storeChosen } = {},
) {
  const profilePath = path.join(__dirname, "resources", ".treeos-profile");
  const firstBootActionsPath = path.join(__dirname, ".first-boot-actions.json");

  if (selected.length === 0) {
    if (fs.existsSync(profilePath)) fs.unlinkSync(profilePath);
    if (fs.existsSync(firstBootActionsPath))
      fs.unlinkSync(firstBootActionsPath);
    console.log("");
    console.log("  Profile cleared. I will awaken seed only.");
    console.log("");
    return;
  }

  fs.writeFileSync(
    profilePath,
    selected.map((e) => e.name).join("\n") + "\n",
    "utf8",
  );
  console.log("");
  console.log(
    `  Profile saved. ${selected.length} extensions will wake with me.`,
  );

  // First-boot actions. Consumed by begin.js after extensions load,
  // before the server listens. The store catalog plants at the story
  // root by default; the peering directory likewise. Operators can move
  // them later.
  const plantTemplates = [];
  if (storeChosen)
    plantTemplates.push({ name: "store:catalog", target: "root" });
  if (peeringChosen)
    plantTemplates.push({ name: "peering:peer-directory", target: "root" });
  if (plantTemplates.length > 0) {
    fs.writeFileSync(
      firstBootActionsPath,
      JSON.stringify({ plantTemplates }, null, 2) + "\n",
      "utf8",
    );
    if (storeChosen) console.log("  Store catalog will plant on first boot.");
    if (peeringChosen)
      console.log(
        "  Peering directory will plant on first boot (when the peering pack ships its seed).",
      );
  } else if (fs.existsSync(firstBootActionsPath)) {
    fs.unlinkSync(firstBootActionsPath);
  }
  console.log("");
}

// ── Entry ──

async function loadEnvIntoProcess() {
  if (!fs.existsSync(envPath)) return {};
  const env = parseEnv(fs.readFileSync(envPath, "utf8"));
  for (const [key, value] of Object.entries(env)) {
    if (!process.env[key]) process.env[key] = value;
  }
  return env;
}

async function boot() {
  // --setup: re-run the extension picker without touching .env.
  if (process.argv.includes("--setup")) {
    await loadEnvIntoProcess();
    await pickExtensions();
    console.log("  Done. Restart me to apply.\n");
    process.exit(0);
  }

  let env = {};
  if (fs.existsSync(envPath)) {
    env = parseEnv(fs.readFileSync(envPath, "utf8"));
    const missing = REQUIRED_KEYS.filter((k) => !env[k]);
    if (missing.length === 0) {
      // I have what I need. Open senses, form body.
      for (const [key, value] of Object.entries(env)) {
        if (!process.env[key]) process.env[key] = value;
      }
      await import("./begin.js");
      return;
    }
    console.log(`\n  Missing required config: ${missing.join(", ")}`);
  }

  // First boot, or .env is incomplete. Run the wizard, then awaken.
  await interactiveSetup(env);
  await loadEnvIntoProcess();
  await import("./begin.js");
}

boot();
