#!/usr/bin/env node
import fs from "fs";
import path from "path";
import crypto from "crypto";
import { fileURLToPath } from "url";
import { createInterface } from "readline/promises";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Check dependencies before anything else
if (!fs.existsSync(path.join(__dirname, "node_modules"))) {
  console.error("\n  Dependencies not installed. Run:\n\n    npm install\n\n  Then try again.\n");
  process.exit(1);
}

// Global error handlers
process.on("unhandledRejection", (err) => {
  console.error("[KERNEL] Unhandled rejection:", err?.message || err);
  if (err?.stack) console.error(err.stack);
});
process.on("uncaughtException", (err) => {
  console.error("[KERNEL] Uncaught exception:", err?.message || err);
  if (err?.stack) console.error(err.stack);
  process.exit(1);
});
const envPath = path.resolve(__dirname, ".env");

const REQUIRED_KEYS = ["MONGODB_URI", "JWT_SECRET", "PORT", "LAND_DOMAIN"];

const DEFAULTS = {
  LAND_DOMAIN: "localhost",
  LAND_NAME: "My Land",
  PORT: "3000",
  MONGODB_URI: "mongodb://localhost:27017/land",
  REQUIRE_EMAIL: "false",
  ENABLE_FRONTEND_HTML: "true",
  HORIZON_URL: "https://horizon.treeos.ai",
};

function parseEnv(content) {
  const env = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (val) env[key] = val;
  }
  return env;
}

function buildEnvFile(values) {
  const domain = values.LAND_DOMAIN;
  const port = values.PORT;
  const isLocal = domain === "localhost" || domain.startsWith("localhost") || domain.startsWith("127.") || domain.startsWith("192.168.") || domain.startsWith("10.") || domain.endsWith(".lan") || domain.endsWith(".local") || !domain.includes(".");
  const protocol = isLocal ? "http" : "https";
  const portSuffix = (port !== "80" && port !== "443") ? `:${port}` : "";
  const landUrl = `${protocol}://${domain}${portSuffix}`;

  return `# Tree Land Node Configuration
# Generated by TreeOS first-run setup
# Runtime settings (LAND_NAME, etc.) are stored in the
# .config system node after first boot. Manage them with: treeos config

# Boot-critical
LAND_DOMAIN=${domain}
PORT=${port}
MONGODB_URI=${values.MONGODB_URI}
JWT_SECRET=${values.JWT_SECRET}
CUSTOM_LLM_API_SECRET_KEY=${values.CUSTOM_LLM_API_SECRET_KEY}

# Seeded into .config node on first boot
LAND_NAME=${values.LAND_NAME}

# Extension settings (read by extensions from .env, not seeded to .config)
REQUIRE_EMAIL=${values.REQUIRE_EMAIL}
ENABLE_FRONTEND_HTML=${values.ENABLE_FRONTEND_HTML}
HORIZON_URL=${values.HORIZON_URL}

# Vite (site/ build)
VITE_LAND_URL=${landUrl}
VITE_LAND_NAME=${values.LAND_NAME}
VITE_TREE_API_URL=${landUrl}/api/v1
`;
}

// ── Setup flow ──

async function interactiveSetup(existingEnv = {}) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log("\n  Welcome to TreeOS.\n");
  console.log("  First-run setup. A few questions to configure your land.\n");

  const ask = async (label, key) => {
    const def = existingEnv[key] || DEFAULTS[key] || "";
    const hint = def ? ` (${def})` : "";
    const answer = await rl.question(`  ${label}${hint}: `);
    return answer.trim() || def;
  };

  // Quick setup option for local development
  const quickAnswer = await rl.question("  Quick setup for localhost? (Y/n): ");
  const quick = !quickAnswer.trim() || quickAnswer.toLowerCase().startsWith("y");

  const values = {};

  if (quick) {
    values.LAND_DOMAIN = "localhost";
    values.LAND_NAME = await ask("Land name", "LAND_NAME");
    values.PORT = "3000";
    values.MONGODB_URI = DEFAULTS.MONGODB_URI;
    values.REQUIRE_EMAIL = "false";
    console.log("\n  Localhost defaults: port 3000, MongoDB localhost:27017/land, no email required.\n");
  } else {
    values.LAND_DOMAIN = (await ask("Domain", "LAND_DOMAIN")).replace(/^https?:\/\//, "").replace(/:\d+$/, "").replace(/\/+$/, "");
    values.LAND_NAME = await ask("Land name", "LAND_NAME");
    values.PORT = await ask("Port", "PORT");
    values.MONGODB_URI = await ask("MongoDB URI", "MONGODB_URI");
    values.REQUIRE_EMAIL = await ask("Require email for registration? (true/false)", "REQUIRE_EMAIL");
  }

  values.JWT_SECRET = existingEnv.JWT_SECRET || crypto.randomBytes(32).toString("hex");
  values.CUSTOM_LLM_API_SECRET_KEY = existingEnv.CUSTOM_LLM_API_SECRET_KEY || crypto.randomBytes(32).toString("hex");
  values.ENABLE_FRONTEND_HTML = existingEnv.ENABLE_FRONTEND_HTML || DEFAULTS.ENABLE_FRONTEND_HTML;
  values.HORIZON_URL = await ask("Horizon URL (empty for standalone)", "HORIZON_URL");

  rl.close();

  fs.writeFileSync(envPath, buildEnvFile(values), "utf8");
  console.log(`\n  Configuration saved to ${envPath}\n`);

  // Extension picker (first-time only)
  await pickExtensions(values.HORIZON_URL);

  console.log("  Starting Land server...\n");
}

// ── Extension bundles ──
// Organized by what they need to run and what they cost in LLM tokens.
// Users pick a profile. Each profile installs the right bundle.

const PROFILES = {
  // Bare minimum: chat/place/query works. No intelligence. No background LLM.
  // For: builders testing, minimal installs, low-power machines.
  minimal: {
    label: "Minimal (chat/place/query only)",
    description: "The tree works. No AI background jobs. No LLM cost when idle.",
    extensions: [
      // Kernel extensions (required for basic operation)
      "treeos-base", "tree-orchestrator", "land-manager", "navigation", "starter-types", "console",
      // Basic functionality
      "values", "html-rendering", "dashboard",
    ],
  },

  // Standard: the tree is alive. Intelligence layers run. Background LLM usage.
  // For: personal use, small teams, anyone with an LLM connection.
  standard: {
    label: "Standard (recommended for most users)",
    description: "Full tree experience. Intelligence, cascade, scheduling. Moderate LLM usage.",
    extensions: [
      // Everything in minimal
      "treeos-base", "tree-orchestrator", "land-manager", "navigation", "starter-types", "console",
      "values", "html-rendering", "dashboard",
      // Core experience
      "notifications", "monitor", "team", "llm-response-formatting",
      "water", "heartbeat", "purpose", "phase", "remember", "approve",
      "deleted-revive", "understanding",
      "user-queries", "book", "llm-failover",
      // Cascade (the nervous system)
      "propagation", "perspective-filter", "sealed-transport", "codebook",
      "gap-detection", "long-memory", "pulse", "flow",
      // Intelligence
      "tree-compress", "contradiction", "inverse-tree", "evolution", "intent", "embed",
      "scout", "explore", "trace", "boundary", "competence", "reflect", "evolve",
      "narrative", "prediction",
      // Maintenance
      "prune", "reroot", "changelog", "digest", "delegate",
      // Infrastructure
      "breath", "scheduler", "schedules",
      "persona", "peer-review", "channels", "taste", "home-memory",
      // Proficiency apps
      "food", "fitness", "recovery", "study", "kb", "life", "sprout",
      "finance", "investor", "market-researcher", "relationships",
      // Core gateways
      "gateway", "gateway-discord", "gateway-telegram", "gateway-reddit",
      // User features
      "instructions", "rings", "dynamic-rename", "stream", "learn", "go",
      "automate", "codebase", "api-keys", "treeos",
      // Bundle meta-extensions
      "treeos-cascade", "treeos-connect", "treeos-intelligence", "treeos-maintenance",
      // Advanced
      "dreams", "browser-bridge", "mycelium", "seed-export", "split", "teach",
      "governance", "backup",
    ],
  },

  // Full: everything. All bundles. All connections. Heavy LLM usage.
  // For: power users, public lands, production deployments.
  full: {
    label: "Full (everything)",
    description: "All extensions. Every gateway, federation, teaching, splitting, and more.",
    extensions: "all",
  },
};

async function pickExtensions(horizonUrl) {
  let extensions = [];
  let isLocal = false;

  // Scan local extensions/ directory first
  const extDir = path.join(__dirname, "extensions");
  if (fs.existsSync(extDir)) {
    const entries = fs.readdirSync(extDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory() || entry.name.startsWith("_") || entry.name.startsWith(".")) continue;
      const manifestPath = path.join(extDir, entry.name, "manifest.js");
      if (fs.existsSync(manifestPath)) {
        try {
          const { pathToFileURL } = await import("url");
          const { default: manifest } = await import(pathToFileURL(manifestPath).href);
          extensions.push({ name: manifest.name || entry.name, version: manifest.version || "1.0.0", local: true });
        } catch {}
      }
    }
    if (extensions.length > 0) {
      isLocal = true;
      console.log(`  Found ${extensions.length} local extensions.\n`);
    }
  }

  // If no local extensions, try Horizon registry
  if (extensions.length === 0 && horizonUrl) {
    try {
      const fetch = globalThis.fetch || (await import("node-fetch")).default;
      console.log(`  Checking extension registry at ${horizonUrl}...`);
      const res = await fetch(`${horizonUrl}/extensions`, {
        headers: { "Content-Type": "application/json" },
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      extensions = data.extensions || [];
    } catch (err) {
      console.log(`  Could not reach registry: ${err.message}`);
    }
  }

  if (extensions.length === 0) {
    console.log("  No extensions found.\n");
    return;
  }

  const rl = (await import("readline/promises")).createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log(`\n  ${extensions.length} extensions available. Choose an install profile:\n`);
  console.log("  1. Minimal     Bare kernel. Chat, place, query only. No apps, no intelligence.");
  console.log("                 Not recommended for regular use. For builders and testing only.\n");
  console.log("  2. Standard    Full tree experience with intelligence, cascade, and apps.");
  console.log("                 Includes food, fitness, study, recovery, KB. Recommended.\n");
  console.log("  3. Full        Everything. All gateways, federation, teaching, splitting.");
  console.log("                 Heavy LLM usage. For production and public lands.\n");
  console.log("  4. Custom      Choose extensions individually by category.\n");

  const choice = (await rl.question("  Choose (1/2/3/4): ")).trim();

  const extMap = {};
  for (const ext of extensions) extMap[ext.name] = ext;

  const finalize = async (selected) => {
    const names = selected.map(e => e.name);
    // Write profile filter FIRST. The loader only loads listed extensions.
    // If remote install fails below, the land boots with only what's on disk
    // that matches the profile. Missing extensions are skipped, not substituted.
    const profilePath = path.join(__dirname, "extensions", ".treeos-profile");
    fs.writeFileSync(profilePath, names.join("\n") + "\n", "utf8");
    console.log(`  Profile saved. ${names.length} extensions will load on boot.\n`);
    if (!isLocal) {
      await installSelected(selected, horizonUrl);
    }
  };

  if (choice === "1") {
    const profile = PROFILES.minimal;
    const selected = profile.extensions.filter(n => extMap[n]).map(n => extMap[n]);
    console.log(`\n  ${profile.label}: ${selected.length} extensions.\n`);
    rl.close();
    return await finalize(selected);
  }

  if (choice === "2") {
    const profile = PROFILES.standard;
    const selected = profile.extensions.filter(n => extMap[n]).map(n => extMap[n]);
    console.log(`\n  ${profile.label}: ${selected.length} extensions.\n`);
    rl.close();
    return await finalize(selected);
  }

  if (choice === "3") {
    console.log(`\n  Full: all ${extensions.length} extensions.\n`);
    rl.close();
    return await finalize(extensions);
  }

  // Custom: category-by-category selection
  const categories = [
    {
      title: "Core (required for chat/place/query)",
      names: ["treeos-base", "tree-orchestrator", "navigation", "starter-types", "console"],
      force: true,
    },
    {
      title: "Interface (dashboard, notifications, formatting)",
      names: ["html-rendering", "dashboard", "notifications", "monitor", "llm-response-formatting", "water", "console"],
      defaultYes: true,
    },
    {
      title: "Cascade (the tree's nervous system, requires LLM for some)",
      names: ["propagation", "perspective-filter", "sealed-transport", "codebook", "gap-detection", "long-memory", "pulse", "flow", "channels"],
      defaultYes: false,
    },
    {
      title: "Intelligence (self-awareness, requires background LLM)",
      names: ["tree-compress", "contradiction", "inverse-tree", "evolution", "intent", "embed", "scout", "explore", "trace", "boundary", "competence", "reflect", "evolve", "rings"],
      defaultYes: false,
    },
    {
      title: "Maintenance (tree hygiene, some require LLM)",
      names: ["prune", "reroot", "changelog", "digest", "delegate"],
      defaultYes: false,
    },
    {
      title: "Tracking and Data",
      names: ["values", "schedules", "prestige", "breath", "scheduler", "heartbeat", "purpose", "phase", "remember"],
      defaultYes: true,
    },
    {
      title: "Social and Teams",
      names: ["team", "approve", "persona", "peer-review"],
      defaultYes: false,
    },
    {
      title: "Connections (gateway channels to Discord, Telegram, etc.)",
      names: ["gateway", "gateway-telegram", "gateway-discord", "gateway-reddit", "gateway-webhook", "gateway-email", "gateway-sms", "gateway-slack", "gateway-matrix", "gateway-x"],
      defaultYes: false,
    },
    {
      title: "Advanced (federation, teaching, splitting)",
      names: ["energy", "transactions", "seed-export", "teach", "split", "governance", "mycelium"],
      defaultYes: false,
    },
    {
      title: "Domain Extensions (fitness, food, etc.)",
      names: ["fitness", "food"],
      defaultYes: false,
    },
  ];

  const selected = [];

  for (const cat of categories) {
    const available = cat.names.filter(n => extMap[n]);
    if (!available.length) continue;

    console.log(`\n  ${cat.title}:`);

    if (cat.force) {
      for (const name of available) {
        console.log(`    ${name} v${extMap[name].version} (required)`);
        selected.push(extMap[name]);
      }
      continue;
    }

    for (const name of available) {
      const ext = extMap[name];
      const hint = cat.defaultYes ? "(Y/n)" : "(y/N)";
      const answer = await rl.question(
        `    ${name} v${ext.version}  ${hint}: `
      );
      const yes = cat.defaultYes
        ? (!answer.trim() || answer.toLowerCase().startsWith("y"))
        : (answer.toLowerCase().startsWith("y"));
      if (yes) selected.push(ext);
    }
  }

  // Catch any extensions not in categories
  const categorized = new Set(categories.flatMap(c => c.names));
  const uncategorized = extensions.filter(e => !categorized.has(e.name));
  if (uncategorized.length) {
    console.log(`\n  Other:`);
    for (const ext of uncategorized) {
      const answer = await rl.question(
        `    ${ext.name} v${ext.version} (y/N): `
      );
      if (answer.toLowerCase().startsWith("y")) selected.push(ext);
    }
  }

  rl.close();

  if (selected.length === 0) {
    console.log("\n  No extensions selected. Install later with: treeos ext install <name>\n");
    return;
  }

  await finalize(selected);
}

async function installSelected(selected, horizonUrl) {
  console.log(`\n  Installing ${selected.length} extensions...\n`);

  const fetch = globalThis.fetch || (await import("node-fetch")).default;
  const extDir = path.join(__dirname, "extensions");

  for (const ext of selected) {
    try {
      const res = await fetch(`${horizonUrl}/extensions/${ext.name}/${ext.version}`, {
        headers: { "Content-Type": "application/json" },
      });
      if (!res.ok) { console.log(`    ${ext.name}: skipped (HTTP ${res.status})`); continue; }

      const data = await res.json();
      if (!data.files || !data.files.length) { console.log(`    ${ext.name}: skipped (no files)`); continue; }

      const targetDir = path.join(extDir, ext.name);
      if (!fs.existsSync(targetDir)) fs.mkdirSync(targetDir, { recursive: true });

      for (const file of data.files) {
        const normalized = path.normalize(file.path);
        if (normalized.startsWith("..") || path.isAbsolute(normalized)) continue;
        const filePath = path.join(targetDir, normalized);
        const fileDir = path.dirname(filePath);
        if (!fs.existsSync(fileDir)) fs.mkdirSync(fileDir, { recursive: true });
        fs.writeFileSync(filePath, file.content, "utf8");
      }

      // Run npm install if the extension declares npm dependencies
      const manifestPath = path.join(targetDir, "manifest.js");
      if (fs.existsSync(manifestPath)) {
        try {
          const { pathToFileURL } = await import("url");
          const { default: manifest } = await import(pathToFileURL(manifestPath).href);
          if (manifest.npm && manifest.npm.length > 0) {
            const deps = {};
            for (const dep of manifest.npm) {
              const scopeEnd = dep.startsWith("@") ? dep.indexOf("/") : -1;
              const atIdx = dep.indexOf("@", scopeEnd + 1);
              if (atIdx > 0) { deps[dep.slice(0, atIdx)] = dep.slice(atIdx + 1); }
              else { deps[dep] = "*"; }
            }
            fs.writeFileSync(path.join(targetDir, "package.json"), JSON.stringify({
              name: `treeos-ext-${ext.name}`, version: "1.0.0", private: true, dependencies: deps,
            }, null, 2), "utf8");

            const { execSync } = await import("child_process");
            execSync("npm install --production --no-fund --no-audit --ignore-scripts", {
              cwd: targetDir, stdio: "pipe", timeout: 60000, shell: true,
            });
            console.log(`    ${ext.name}: npm dependencies installed`);
          }
        } catch (npmErr) {
          console.log(`    ${ext.name}: npm install failed (${npmErr.message}). Will retry on boot.`);
        }
      }

      console.log(`    ${ext.name} v${ext.version} (${data.files.length} files)`);
    } catch (err) {
      console.log(`    ${ext.name}: failed (${err.message})`);
    }
  }

  console.log();
}

async function boot() {
  // node boot.js --setup: re-run extension picker without touching .env
  if (process.argv.includes("--setup")) {
    if (fs.existsSync(envPath)) {
      const env = parseEnv(fs.readFileSync(envPath, "utf8"));
      for (const [key, value] of Object.entries(env)) {
        if (!process.env[key]) process.env[key] = value;
      }
    }
    await pickExtensions(process.env.HORIZON_URL || DEFAULTS.HORIZON_URL);
    console.log("  Done. Restart the server to apply.\n");
    process.exit(0);
  }

  let existingEnv = {};

  if (fs.existsSync(envPath)) {
    existingEnv = parseEnv(fs.readFileSync(envPath, "utf8"));
    const missing = REQUIRED_KEYS.filter((k) => !existingEnv[k]);

    if (missing.length === 0) {
      // Load .env into process.env BEFORE importing server.js.
      for (const [key, value] of Object.entries(existingEnv)) {
        if (!process.env[key]) process.env[key] = value;
      }
      await import("./server.js");
      return;
    }

    console.log(
      `\n  Missing required config: ${missing.join(", ")}`
    );
    await interactiveSetup(existingEnv);
  } else {
    await interactiveSetup();
  }

  // Reload env and boot
  const freshEnv = parseEnv(fs.readFileSync(envPath, "utf8"));
  for (const [key, value] of Object.entries(freshEnv)) {
    if (!process.env[key]) process.env[key] = value;
  }
  await import("./server.js");
}

boot();
