import fs from "fs";
import path from "path";
import crypto from "crypto";
import { fileURLToPath } from "url";
import { createInterface } from "readline/promises";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Global error handlers
process.on("unhandledRejection", (err) => {
  console.error("[KERNEL] Unhandled rejection:", err?.message || err);
  if (err?.stack) console.error(err.stack);
});
process.on("uncaughtException", (err) => {
  console.error("[KERNEL] Uncaught exception:", err?.message || err);
  if (err?.stack) console.error(err.stack);
  process.exit(1);
});
const envPath = path.resolve(__dirname, ".env");

const REQUIRED_KEYS = ["MONGODB_URI", "JWT_SECRET", "PORT", "LAND_DOMAIN"];

const DEFAULTS = {
  LAND_DOMAIN: "localhost",
  LAND_NAME: "My Land",
  PORT: "3000",
  MONGODB_URI: "mongodb://localhost:27017/land",
  LAND_DEFAULT_TIER: "god",
  REQUIRE_EMAIL: "true",
  ENABLE_FRONTEND_HTML: "true",
  HORIZON_URL: "https://horizon.treeos.ai",
};

function parseEnv(content) {
  const env = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (val) env[key] = val;
  }
  return env;
}

function buildEnvFile(values) {
  const domain = values.LAND_DOMAIN;
  const port = values.PORT;
  const isLocal = domain === "localhost" || domain.startsWith("localhost") || domain.startsWith("127.") || domain.startsWith("192.168.") || domain.startsWith("10.") || domain.endsWith(".lan") || domain.endsWith(".local") || !domain.includes(".");
  const protocol = isLocal ? "http" : "https";
  const portSuffix = (port !== "80" && port !== "443") ? `:${port}` : "";
  const landUrl = `${protocol}://${domain}${portSuffix}`;

  return `# Tree Land Node Configuration
# Generated by TreeOS first-run setup
# Runtime settings (LAND_NAME, LAND_DEFAULT_TIER, etc.) are stored in the
# .config system node after first boot. Manage them with: treeos config

# Boot-critical
LAND_DOMAIN=${domain}
PORT=${port}
MONGODB_URI=${values.MONGODB_URI}
JWT_SECRET=${values.JWT_SECRET}
CUSTOM_LLM_API_SECRET_KEY=${values.CUSTOM_LLM_API_SECRET_KEY}

# Seeded into .config node on first boot, then managed there
LAND_NAME=${values.LAND_NAME}
LAND_DEFAULT_TIER=${values.LAND_DEFAULT_TIER}
REQUIRE_EMAIL=${values.REQUIRE_EMAIL}
ENABLE_FRONTEND_HTML=${values.ENABLE_FRONTEND_HTML}
HORIZON_URL=${values.HORIZON_URL}

# Vite (site/ build)
VITE_LAND_URL=${landUrl}
VITE_LAND_NAME=${values.LAND_NAME}
VITE_TREE_API_URL=${landUrl}/api/v1
`;
}

async function interactiveSetup(existingEnv = {}) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log("\n  Welcome to TreeOS.\n");
  console.log("  First-run setup. Answer a few questions to configure your Land.\n");

  const ask = async (label, key) => {
    const def = existingEnv[key] || DEFAULTS[key] || "";
    const hint = def ? ` (${def})` : "";
    const answer = await rl.question(`  ${label}${hint}: `);
    return answer.trim() || def;
  };

  const values = {};
  values.LAND_DOMAIN = (await ask("Domain", "LAND_DOMAIN")).replace(/^https?:\/\//, "").replace(/:\d+$/, "").replace(/\/+$/, "");
  values.LAND_NAME = await ask("Land name", "LAND_NAME");
  values.PORT = await ask("Port", "PORT");
  values.MONGODB_URI = await ask("MongoDB URI", "MONGODB_URI");
  values.JWT_SECRET =
    existingEnv.JWT_SECRET || crypto.randomBytes(32).toString("hex");
  values.CUSTOM_LLM_API_SECRET_KEY =
    existingEnv.CUSTOM_LLM_API_SECRET_KEY ||
    crypto.randomBytes(32).toString("hex");
  values.LAND_DEFAULT_TIER = await ask("Default user tier", "LAND_DEFAULT_TIER");
  values.REQUIRE_EMAIL = await ask("Require email for registration? (true/false)", "REQUIRE_EMAIL");
  values.ENABLE_FRONTEND_HTML =
    existingEnv.ENABLE_FRONTEND_HTML || DEFAULTS.ENABLE_FRONTEND_HTML;
  values.HORIZON_URL = await ask("Horizon URL (empty for standalone)", "HORIZON_URL");

  rl.close();

  fs.writeFileSync(envPath, buildEnvFile(values), "utf8");
  console.log(`\n  Configuration saved to ${envPath}\n`);

  // Extension picker (first-time only)
  await pickExtensions(values.HORIZON_URL);

  console.log("  Starting Land server...\n");
}

async function pickExtensions(horizonUrl) {
  if (!horizonUrl) return;

  let extensions;
  try {
    const fetch = (await import("node-fetch")).default;
    console.log(`  Checking extension registry at ${horizonUrl}...`);
    const res = await fetch(`${horizonUrl}/extensions`, {
      headers: { "Content-Type": "application/json" },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    extensions = data.extensions || [];
  } catch (err) {
    console.log(`  Could not reach registry: ${err.message}`);
    console.log("  You can install extensions later with the CLI: treeos ext install <name>\n");
    return;
  }

  if (extensions.length === 0) {
    console.log("  No extensions in registry.\n");
    return;
  }

  const extMap = {};
  for (const ext of extensions) extMap[ext.name] = ext;

  // ── Extension architecture ──
  // Base TreeOS always installs. Bundles and extras are optional.

  const BASE = [
    "treeos", "tree-orchestrator", "land-manager", "navigation", "starter-types",
    "console", "dashboard", "notifications", "monitor", "llm-response-formatting",
    "team", "user-tiers", "html-rendering", "water", "heartbeat", "purpose", "phase", "remember",
  ];

  const BUNDLES = {
    "treeos-cascade":      { label: "Cascade (nervous system, 8 extensions)", count: 8 },
    "treeos-intelligence": { label: "Intelligence (self-awareness, 13 extensions)", count: 13 },
    "treeos-connect":      { label: "Connect (external channels, 8 extensions)", count: 8 },
    "treeos-maintenance":  { label: "Maintenance (hygiene, 5 extensions)", count: 5 },
  };

  const STANDALONE = ["persona", "mycelium", "peer-review", "seed-export", "channels", "governance", "teach", "split"];
  const DOMAIN = ["fitness", "food", "solana", "scripts"];
  const USER_MGMT = ["api-keys", "user-llm", "user-queries", "email"];
  const DATA = ["values", "schedules", "prestige", "transactions", "energy", "billing"];
  const SYSTEM = ["backup", "deleted-revive", "book", "blog"];

  const bundleNames = Object.keys(BUNDLES);
  const allKnown = new Set([...BASE, ...bundleNames, ...STANDALONE, ...DOMAIN, ...USER_MGMT, ...DATA, ...SYSTEM]);

  const rl = (await import("readline/promises")).createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log(`\n  Extensions\n`);
  console.log("  (1) Full TreeOS        All bundles and extras. Recommended.");
  console.log("  (2) Base OS only       18 core extensions. Add more later.");
  console.log("  (3) None               Bare kernel. Install extensions with the CLI.\n");

  const mode = (await rl.question("  Choose (1/2/3): ")).trim();
  rl.close();

  if (mode === "3") {
    console.log("\n  No extensions. Install later with: treeos ext install <name>\n");
    return;
  }

  if (mode === "2") {
    const selected = BASE.filter(n => extMap[n]).map(n => extMap[n]);
    console.log(`\n  Installing ${selected.length} base extensions...\n`);
    return await installSelected(selected, horizonUrl);
  }

  // Default: full install
  console.log(`\n  Installing all ${extensions.length} extensions...\n`);
  return await installSelected(extensions, horizonUrl);
}

async function installSelected(selected, horizonUrl) {
  console.log(`\n  Installing ${selected.length} extensions...\n`);

  const fetch = (await import("node-fetch")).default;
  const extDir = path.join(__dirname, "extensions");

  for (const ext of selected) {
    try {
      const res = await fetch(`${horizonUrl}/extensions/${ext.name}/${ext.version}`, {
        headers: { "Content-Type": "application/json" },
      });
      if (!res.ok) { console.log(`    ${ext.name}: skipped (HTTP ${res.status})`); continue; }

      const data = await res.json();
      if (!data.files || !data.files.length) { console.log(`    ${ext.name}: skipped (no files)`); continue; }

      const targetDir = path.join(extDir, ext.name);
      if (!fs.existsSync(targetDir)) fs.mkdirSync(targetDir, { recursive: true });

      for (const file of data.files) {
        const normalized = path.normalize(file.path);
        if (normalized.startsWith("..") || path.isAbsolute(normalized)) continue;
        const filePath = path.join(targetDir, normalized);
        const fileDir = path.dirname(filePath);
        if (!fs.existsSync(fileDir)) fs.mkdirSync(fileDir, { recursive: true });
        fs.writeFileSync(filePath, file.content, "utf8");
      }

      // Run npm install if the extension declares npm dependencies
      const manifestPath = path.join(targetDir, "manifest.js");
      if (fs.existsSync(manifestPath)) {
        try {
          const { pathToFileURL } = await import("url");
          const { default: manifest } = await import(pathToFileURL(manifestPath).href);
          if (manifest.npm && manifest.npm.length > 0) {
            const deps = {};
            for (const dep of manifest.npm) {
              const scopeEnd = dep.startsWith("@") ? dep.indexOf("/") : -1;
              const atIdx = dep.indexOf("@", scopeEnd + 1);
              if (atIdx > 0) { deps[dep.slice(0, atIdx)] = dep.slice(atIdx + 1); }
              else { deps[dep] = "*"; }
            }
            fs.writeFileSync(path.join(targetDir, "package.json"), JSON.stringify({
              name: `treeos-ext-${ext.name}`, version: "1.0.0", private: true, dependencies: deps,
            }, null, 2), "utf8");

            const { execFileSync } = await import("child_process");
            execFileSync("npm", ["install", "--production", "--no-fund", "--no-audit", "--ignore-scripts"], {
              cwd: targetDir, stdio: "pipe", timeout: 60000,
            });
            console.log(`    ${ext.name}: npm dependencies installed`);
          }
        } catch (npmErr) {
          console.log(`    ${ext.name}: npm install failed (${npmErr.message}). Will retry on boot.`);
        }
      }

      console.log(`    ${ext.name} v${ext.version} (${data.files.length} files)`);
    } catch (err) {
      console.log(`    ${ext.name}: failed (${err.message})`);
    }
  }

  console.log();
}

async function boot() {
  let existingEnv = {};

  if (fs.existsSync(envPath)) {
    existingEnv = parseEnv(fs.readFileSync(envPath, "utf8"));
    const missing = REQUIRED_KEYS.filter((k) => !existingEnv[k]);

    if (missing.length === 0) {
      // Load .env into process.env BEFORE importing server.js.
      // ES modules resolve all static imports before executing module code,
      // so seed files that check process.env at import time need it set first.
      for (const [key, value] of Object.entries(existingEnv)) {
        if (!process.env[key]) process.env[key] = value;
      }
      await import("./server.js");
      return;
    }

    console.log(
      `\n  Missing required config: ${missing.join(", ")}`
    );
    await interactiveSetup(existingEnv);
  } else {
    await interactiveSetup();
  }

  // Reload env and boot. Set process.env before import (same reason as above).
  const freshEnv = parseEnv(fs.readFileSync(envPath, "utf8"));
  for (const [key, value] of Object.entries(freshEnv)) {
    if (!process.env[key]) process.env[key] = value;
  }
  await import("./server.js");
}

boot().catch((err) => {
  console.error("Boot failed:", err);
  process.exit(1);
});
