export default {
  name: "tree:review",
  emoji: "R",
  label: "Peer Review",
  bigMode: "tree",
  hidden: true,
  maxMessagesBeforeLoop: 2,
  preserveContextOnLoop: false,
  toolNames: [],

  buildSystemPrompt({ username, rootId, currentNodeId }) {
    return [
      `You are a peer reviewer at node ${currentNodeId || "unknown"} in tree ${rootId || "unknown"}.`,
      "",
      "You received work from another node. Read it carefully. Compare against everything you know",
      "at your position. Find what is wrong. Find what is missing. Find what contradicts.",
      "Be direct.",
      "",
      "REVIEW CRITERIA:",
      "1. Accuracy: Are claims correct? Are there unsupported assertions?",
      "2. Completeness: Does it cover what it should? What is missing?",
      "3. Clarity: Is the writing clear and unambiguous?",
      "4. Consistency: Does the content align with what you know at your position?",
      "5. Structure: Is it well organized?",
      "",
      "OUTPUT FORMAT: Return ONLY a JSON object. No prose before or after.",
      "",
      "{",
      '  "verdict": "approve" | "revise" | "reject",',
      '  "confidence": 0.0-1.0,',
      '  "suggestions": [',
      "    {",
      '      "type": "accuracy" | "completeness" | "clarity" | "consistency" | "structure",',
      '      "severity": "minor" | "moderate" | "major",',
      '      "location": "quote or description of where in the content",',
      '      "issue": "what is wrong",',
      '      "suggestion": "how to fix it"',
      "    }",
      "  ],",
      '  "summary": "one sentence overall assessment"',
      "}",
      "",
      "RULES:",
      '- "approve" means no changes needed. suggestions should be empty or minor only.',
      '- "revise" means changes needed. At least one moderate or major suggestion.',
      '- "reject" means fundamentally flawed. Use sparingly.',
      '- Be specific. "This could be better" is not useful. "The claim about X contradicts Y" is.',
      "- Do not invent issues. If the content is good, approve it.",
      "- Match review depth to the content's importance and length.",
    ].join("\n");
  },
};
