// TreeOS IBP — scheduled-wake registry.
//
// Beings declare a wake cadence ("wake me every N ms"); a single tick
// loop walks the registry and emits SUMMONs (intent="scheduled-wake")
// to whichever beings are due. Substrate's third summon-source after
// direct being-to-being SUMMONs and DO-trigger fan-out (the universal
// bridge for code-emitted DOs).
//
// **Why one registry / one tick.** Each being having its own timer
// would multiply Node intervals and lose visibility into who's
// scheduled. One central tick walking a shared registry stays cheap
// and inspectable — getStats() always says exactly what's scheduled.
//
// **Two-mode neutrality.** The default emitter writes SUMMONs as
// `<land>/@scheduler` (synthesized system stance, Mode 2 flavor).
// Lands that want the embodied flavor (Mode 1) install a scheduler-
// being extension that calls `setEmitter()` to swap in its own
// dispatcher — the registry doesn't change.
//
// **Schedule shape:**
//
//   {
//     id:        string,                   // generated by schedule()
//     beingId:   string,                   // who gets summoned
//     intervalMs:number,                   // wake every N ms (minimum 250ms)
//     intent:    "scheduled-wake" | string,// SUMMON intent on emission
//     priority:  number,                   // SUMMON priority; default 4 (BACKGROUND)
//     content:   any,                      // payload of the wake SUMMON
//     nextFireMs:number,                   // when the next wake fires (computed)
//     lastFireMs:number | null,            // last time the wake fired
//     skipIfBacklog:boolean,               // skip wake when being already has unconsumed scheduled-wakes (default true)
//   }
//
// Cron-style scheduling and event-condition triggers ("when phase == awake")
// land later if a real subscription needs them. For now: simple intervals,
// which covers every existing OrchestratorRuntime user (scout, dreams,
// compress, peer-review, etc. — all interval-based).

import { randomUUID } from "crypto";
import log from "../../seed/core/log.js";
import { appendToInbox } from "./inbox.js";
import { wake } from "./scheduler.js";
import { getLandDomain } from "./address.js";
import { getLandRootId } from "../../seed/landRoot.js";

const MIN_INTERVAL_MS = 250;
const DEFAULT_TICK_MS = 1000;

// scheduleId -> schedule entry
const _registry = new Map();

// beingId -> Set<scheduleId>
const _byBeing = new Map();

let _tickHandle = null;
let _tickMs = DEFAULT_TICK_MS;
let _emitter = _defaultEmitter;

// ────────────────────────────────────────────────────────────────
// Public API
// ────────────────────────────────────────────────────────────────

/**
 * Register a wake schedule for a being. Returns the schedule id.
 *
 * @param {string} beingId
 * @param {object} opts
 * @param {number} opts.intervalMs       wake cadence (>=250ms)
 * @param {string} [opts.intent]         SUMMON intent; default "scheduled-wake"
 * @param {number} [opts.priority]       SUMMON priority; default 4
 * @param {any}    [opts.content]        SUMMON content; default { kind: "scheduled-wake" }
 * @param {boolean}[opts.skipIfBacklog]  skip wake when being already has unconsumed scheduled-wake (default true)
 * @param {string} [opts.id]             caller-supplied stable id (so re-registers replace)
 * @returns {string} schedule id
 */
export function schedule(beingId, opts = {}) {
  if (!beingId || typeof beingId !== "string") {
    throw new Error("schedule requires beingId");
  }
  const intervalMs = Number(opts.intervalMs);
  if (!Number.isFinite(intervalMs) || intervalMs < MIN_INTERVAL_MS) {
    throw new Error(`schedule.intervalMs must be a number >= ${MIN_INTERVAL_MS}`);
  }

  const id = opts.id || randomUUID();
  // Idempotent re-register: if the id already exists, replace it.
  unschedule(id);

  const now = Date.now();
  const entry = {
    id,
    beingId:       String(beingId),
    intervalMs,
    intent:        opts.intent || "scheduled-wake",
    priority:      Number.isFinite(opts.priority) ? Number(opts.priority) : 4,
    content:       opts.content !== undefined ? opts.content : { kind: "scheduled-wake" },
    skipIfBacklog: opts.skipIfBacklog !== false,
    nextFireMs:    now + intervalMs,
    lastFireMs:    null,
  };

  _registry.set(id, entry);
  let beingSet = _byBeing.get(entry.beingId);
  if (!beingSet) {
    beingSet = new Set();
    _byBeing.set(entry.beingId, beingSet);
  }
  beingSet.add(id);

  log.verbose("Schedule",
    `scheduled wake for being ${entry.beingId.slice(0, 8)} every ${intervalMs}ms ` +
    `(id=${id.slice(0, 8)})`);
  return id;
}

/**
 * Remove one schedule. Returns true when something was removed.
 */
export function unschedule(scheduleId) {
  const entry = _registry.get(scheduleId);
  if (!entry) return false;
  _registry.delete(scheduleId);
  const beingSet = _byBeing.get(entry.beingId);
  if (beingSet) {
    beingSet.delete(scheduleId);
    if (beingSet.size === 0) _byBeing.delete(entry.beingId);
  }
  return true;
}

/**
 * Drop every schedule for a being. Called on being deletion.
 */
export function unscheduleAllForBeing(beingId) {
  if (!beingId) return 0;
  const beingSet = _byBeing.get(String(beingId));
  if (!beingSet) return 0;
  const ids = Array.from(beingSet);
  for (const id of ids) unschedule(id);
  return ids.length;
}

/**
 * Start the tick loop. Idempotent; calling twice keeps the existing
 * timer. Pass `{ tickMs }` to override the cadence (default 1s).
 */
export function startTickLoop({ tickMs } = {}) {
  if (Number.isFinite(tickMs) && tickMs >= MIN_INTERVAL_MS) {
    _tickMs = tickMs;
  }
  if (_tickHandle) return;
  _tickHandle = setInterval(() => {
    runOnce(Date.now()).catch((err) => {
      log.error("Schedule", `tick failed: ${err.message}`);
    });
  }, _tickMs);
  // Don't keep the process alive solely on the schedule tick — server
  // shutdown handles its own lifecycle. Node's unref makes setInterval
  // non-blocking for exit purposes.
  if (typeof _tickHandle.unref === "function") _tickHandle.unref();
  log.info("Schedule", `tick loop started (every ${_tickMs}ms)`);
}

/**
 * Stop the tick loop. Idempotent.
 */
export function stopTickLoop() {
  if (!_tickHandle) return;
  clearInterval(_tickHandle);
  _tickHandle = null;
  log.info("Schedule", "tick loop stopped");
}

/**
 * Run one tick manually. Used by the periodic loop and by tests.
 * Walks every registered schedule and fires wakes for schedules whose
 * nextFireMs has passed. Updates lastFireMs/nextFireMs on fire.
 *
 * @param {number} [nowMs]   override the clock (tests)
 * @returns {Promise<number>} number of wakes emitted
 */
export async function runOnce(nowMs) {
  const now = Number.isFinite(nowMs) ? nowMs : Date.now();
  let fired = 0;
  for (const entry of _registry.values()) {
    if (entry.nextFireMs > now) continue;
    try {
      await _emitter(entry, now);
      fired++;
    } catch (err) {
      log.warn("Schedule",
        `emit failed for schedule ${entry.id.slice(0, 8)} (being ${entry.beingId.slice(0, 8)}): ${err.message}`);
    } finally {
      entry.lastFireMs = now;
      // Advance to the next interval beyond now. If many intervals
      // were missed (e.g. host slept), skip the catch-up: one wake is
      // enough; the being doesn't need to drown.
      const missed = Math.max(1, Math.floor((now - entry.nextFireMs) / entry.intervalMs) + 1);
      entry.nextFireMs = now + (missed > 1 ? entry.intervalMs : entry.intervalMs);
      // Equivalent to: entry.nextFireMs = now + entry.intervalMs;
      // The branch is left explicit so future "preserve cadence even
      // after a long sleep" mode is a one-line change.
    }
  }
  return fired;
}

/**
 * Swap the default emitter. Used by the embodied scheduler-being
 * extension to route scheduled wakes through itself (Mode 1) instead
 * of the synthesized @system sender (Mode 2).
 *
 * @param {function(entry, nowMs): Promise<void>} fn
 */
export function setEmitter(fn) {
  _emitter = typeof fn === "function" ? fn : _defaultEmitter;
}

/**
 * Restore the default code-flavored emitter.
 */
export function resetEmitter() {
  _emitter = _defaultEmitter;
}

/**
 * Diagnostic snapshot.
 */
export function getStats() {
  return {
    totalSchedules:        _registry.size,
    beingsWithSchedules:   _byBeing.size,
    tickRunning:           !!_tickHandle,
    tickMs:                _tickMs,
    emitter:               _emitter === _defaultEmitter ? "default" : "custom",
  };
}

/**
 * For tests / teardown.
 */
export function _resetAll() {
  stopTickLoop();
  _registry.clear();
  _byBeing.clear();
  _emitter = _defaultEmitter;
  _tickMs = DEFAULT_TICK_MS;
}

// ────────────────────────────────────────────────────────────────
// Internals
// ────────────────────────────────────────────────────────────────

async function _defaultEmitter(entry, nowMs) {
  const sender = `${getLandDomain() || "land"}/@scheduler`;
  const correlation = randomUUID();
  const nodeId = getLandRootId() || null;
  if (!nodeId) {
    log.debug("Schedule", `skipping wake for being ${entry.beingId.slice(0, 8)}: land root not initialized`);
    return;
  }
  await appendToInbox(nodeId, entry.beingId, {
    from:            sender,
    content:         entry.content,
    intent:          entry.intent,
    correlation,
    rootCorrelation: correlation,  // each scheduled wake is its own root
    priority:        entry.priority,
    sentAt:          new Date(nowMs).toISOString(),
  });
  wake(entry.beingId, nodeId);
}
