// DATA ONLY — no logic generation. Walks `words/` + `book/`, embeds every `.word` via include_str!
// into a manifest (so the treeos binary carries its own store), and asserts the store's structural
// invariants at build time:
//
//   1. every floor `.rs` inside `words/` has at least one sibling `.word` — a floor with no word
//      beside it is drift (the seam law: meaning in .word, floor in .rs, ADJACENT);
//   2. coined word names are UNIQUE outside `words/ables/` (the able-specs are their own namespace,
//      resolved as `the able <name>`), so a bare `I read <word>.` always lands on one file.
//
// Generated: $OUT_DIR/words_gen.rs with `static WORDS/BOOK: &[(&str, &str)]` (store-relative path →
// embedded text), included by src/lib.rs. Anything smarter (lookup, order, drift checks) lives in
// src/lib.rs as ordinary reviewable Rust.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

fn walk_words(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for ent in rd.flatten() {
        let p = ent.path();
        if p.is_dir() {
            walk_words(&p, out);
        } else if p.extension().and_then(|e| e.to_str()) == Some("word") {
            out.push(p);
        }
    }
}

/// The name a file coins as (treebook::op_word_name): the file STEM, literally. The transitional
/// `create`/`index` coin-as-bundle-dir exception died with the M1C rename (`create-space`→`makespace`;
/// every stem is the coined name now — one word, one token).
fn coined_name(p: &Path) -> String {
    p.file_stem().and_then(|s| s.to_str()).unwrap_or("").to_string()
}

fn main() {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    println!("cargo:rerun-if-changed={}", root.join("words").display());
    println!("cargo:rerun-if-changed={}", root.join("book").display());

    let (words_dir, book_dir) = (root.join("words"), root.join("book"));
    let mut words = Vec::new();
    walk_words(&words_dir, &mut words);
    let mut book = Vec::new();
    walk_words(&book_dir, &mut book);
    words.sort();
    book.sort();

    // invariant 1: every floor .rs has a sibling .word in its bundle dir.
    let mut rs = Vec::new();
    let mut stack = vec![words_dir.clone()];
    while let Some(d) = stack.pop() {
        let Ok(rd) = std::fs::read_dir(&d) else { continue };
        for ent in rd.flatten() {
            let p = ent.path();
            if p.is_dir() {
                stack.push(p);
            } else if p.extension().and_then(|e| e.to_str()) == Some("rs") {
                rs.push(p);
            }
        }
    }
    for r in &rs {
        let dir = r.parent().unwrap();
        let has_word = std::fs::read_dir(dir)
            .map(|rd| rd.flatten().any(|e| e.path().extension().and_then(|x| x.to_str()) == Some("word")))
            .unwrap_or(false);
        assert!(
            has_word,
            "STORE DRIFT: floor {} has NO sibling .word — a floor with no word beside it is drift; \
             author the word or move the floor",
            r.display()
        );
    }

    // invariant 2: coined names unique outside ables/.
    let mut seen: HashMap<String, PathBuf> = HashMap::new();
    for w in &words {
        let rel = w.strip_prefix(&root).unwrap();
        if rel.starts_with("words/ables") {
            continue;
        }
        let name = coined_name(w);
        if let Some(prev) = seen.insert(name.clone(), w.clone()) {
            panic!(
                "STORE DRIFT: coined name `{name}` is claimed by BOTH {} and {} — `I read {name}.` \
                 must land on exactly one file",
                prev.display(),
                w.display()
            );
        }
    }

    // emit the manifest.
    let mut gen = String::from("// generated by build.rs — DATA ONLY. (rel-path, embedded text) pairs.\n");
    for (name, set) in [("WORDS", &words), ("BOOK", &book)] {
        gen.push_str(&format!("pub(crate) static {name}: &[(&str, &str)] = &[\n"));
        for p in set.iter() {
            let rel = p.strip_prefix(&root).unwrap().to_string_lossy().replace('\\', "/");
            gen.push_str(&format!("    ({rel:?}, include_str!({:?})),\n", p.display().to_string()));
        }
        gen.push_str("];\n");
    }
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("words_gen.rs");
    std::fs::write(out, gen).unwrap();
}
