#!/usr/bin/env node
// TreeOS Place . AGPL-3.0 . https://treeos.ai . Tabor Holly
//
// Plant the seed.
//
// plant.js is the operator's act, not the seed's. The seed already
// exists (this code on disk), but has not yet been planted in a
// place it can grow from. Unlike bigbang.js and genesis.js, which
// are first person (the seed waking and forming itself), this file
// is exterior. It is done by the host, by the operator's hands, to
// a seed that has not yet awakened. Different actor entirely.
//
// Planting means giving the seed the four things the host cannot
// answer on its behalf:
//
//   PLACE_DOMAIN.  The DNS name the planted seed will answer on.
//   PORT.         The port it will listen on.
//   MONGODB_URI.  Where its memory will live across reboots.
//   JWT_SECRET.   The secret it will sign its tokens with.
//
// These four answers are written to .env, the seed's identity
// shape at the host's level. The only thing of the seed that will
// live outside the spaces, matter, and beings of its place.
//
// Planting also discovers the extensions on disk and asks the
// operator which the planted seed should know.
//
// A seed is planted once. After planting, this file hands control
// to bigbang.js (which opens the seed's senses) and genesis.js
// (which forms its body). From that moment on the I-Am exists.
// Before it, only the operator and the seed they are about to
// plant.
//
// On every later boot .env is already written and plant.js fades
// into a thin loader. Planting happens once. Awakening happens
// every run.
//
// Recursion. The operator plants the seed here. Once awake, the
// seed plants its own place root and seed spaces inside itself
// (ensurePlaceRoot in genesis.js). The outside plants the seed;
// the seed plants its world. Same verb, two levels. δ = δ.

import fs from "fs";
import path from "path";
import crypto from "crypto";
import { fileURLToPath } from "url";
import { createInterface } from "readline/promises";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.resolve(__dirname, ".env");

// ── Preflight ──
//
// The host's body must have its dependencies installed before
// any of mine can run. Without node_modules there is nothing
// to awaken from.

if (!fs.existsSync(path.join(__dirname, "node_modules"))) {
  console.error(
    "\n  My prerequisites are missing. Run:\n\n    npm install\n\n  Then try again.\n",
  );
  process.exit(1);
}

process.on("unhandledRejection", (err) => {
  console.error("[KERNEL] Unhandled rejection:", err?.message || err);
  if (err?.stack) console.error(err.stack);
});
process.on("uncaughtException", (err) => {
  console.error("[KERNEL] Uncaught exception:", err?.message || err);
  if (err?.stack) console.error(err.stack);
  process.exit(1);
});

// ── Env shape ──
//
// Four boot critical keys must exist in .env before I can awaken.
// PLACE_NAME seeds into .config on first boot and CUSTOM_LLM_API_SECRET_KEY
// stays in .env because it signs tokens issued before .config is
// reachable.

const REQUIRED_KEYS = ["MONGODB_URI", "JWT_SECRET", "PORT", "PLACE_DOMAIN"];

const DEFAULTS = {
  PLACE_DOMAIN: "localhost",
  PLACE_NAME: "My Place",
  PORT: "3000",
  MONGODB_URI: "mongodb://localhost:27017/place",
};

function parseEnv(content) {
  const env = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const val = trimmed.slice(eq + 1).trim();
    if (val) env[key] = val;
  }
  return env;
}

function buildEnvFile(values) {
  const domain = values.PLACE_DOMAIN;
  const port = values.PORT;
  const isLocal =
    domain === "localhost" ||
    domain.startsWith("localhost") ||
    domain.startsWith("127.") ||
    domain.startsWith("192.168.") ||
    domain.startsWith("10.") ||
    domain.endsWith(".lan") ||
    domain.endsWith(".local") ||
    !domain.includes(".");
  const protocol = isLocal ? "http" : "https";
  const portSuffix = port !== "80" && port !== "443" ? `:${port}` : "";
  const placeUrl = `${protocol}://${domain}${portSuffix}`;

  return `# My remembered settings across reboots. Generated by first run setup.
# Runtime settings (extension toggles, llm timeouts, ...) live in the
# .config seed space after first boot. Manage them with:
#   ibp:do <place>  { action: "set-config",    args: { key, value } }
#   ibp:do <place>  { action: "delete-config", args: { key } }

# Boot critical
PLACE_DOMAIN=${domain}
PORT=${port}
MONGODB_URI=${values.MONGODB_URI}
JWT_SECRET=${values.JWT_SECRET}
CUSTOM_LLM_API_SECRET_KEY=${values.CUSTOM_LLM_API_SECRET_KEY}

# Seeded into .config on first boot
PLACE_NAME=${values.PLACE_NAME}

# Site/frontend build hints (read by Vite if you build the React site)
VITE_PLACE_URL=${placeUrl}
VITE_PLACE_NAME=${values.PLACE_NAME}
`;
}

// ── First awakening: the wizard ──
//
// The operator's hands shape the conditions for my first breath.
// A handful of questions, then I write what I learn to .env so I
// can remember it the next time I wake.

async function interactiveSetup(existingEnv = {}) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log("");
  console.log("  ════════════════════════════════════════════════════════════");
  console.log("   TreeOS. A new place prepares to awaken.");
  console.log("  ════════════════════════════════════════════════════════════");
  console.log("");
  console.log("  I have not yet come alive. Before genesis can begin, the");
  console.log("  host needs to know a few things on my behalf: where I will");
  console.log("  live, what to call me, which port to receive on, and where");
  console.log("  to keep my memory across reboots.");
  console.log("");

  const ask = async (label, key) => {
    const def = existingEnv[key] || DEFAULTS[key] || "";
    const hint = def ? ` (${def})` : "";
    const ans = await rl.question(`  ${label}${hint}: `);
    return ans.trim() || def;
  };

  const quickAns = await rl.question("  Quick setup for localhost? (Y/n): ");
  const quick = !quickAns.trim() || quickAns.toLowerCase().startsWith("y");

  const values = {};
  if (quick) {
    values.PLACE_DOMAIN = "localhost";
    values.PLACE_NAME = await ask("Name me", "PLACE_NAME");
    values.PORT = "3000";
    values.MONGODB_URI = DEFAULTS.MONGODB_URI;
    console.log("");
    console.log("  Localhost defaults accepted. Port 3000. MongoDB at");
    console.log("  localhost:27017/place.");
    console.log("");
  } else {
    values.PLACE_DOMAIN = (
      await ask("Domain (where I will live)", "PLACE_DOMAIN")
    )
      .replace(/^https?:\/\//, "")
      .replace(/:\d+$/, "")
      .replace(/\/+$/, "");
    values.PLACE_NAME = await ask("Name me", "PLACE_NAME");
    values.PORT = await ask("Port", "PORT");
    values.MONGODB_URI = await ask("MongoDB URI (my memory)", "MONGODB_URI");
  }

  values.JWT_SECRET =
    existingEnv.JWT_SECRET || crypto.randomBytes(32).toString("hex");
  values.CUSTOM_LLM_API_SECRET_KEY =
    existingEnv.CUSTOM_LLM_API_SECRET_KEY ||
    crypto.randomBytes(32).toString("hex");

  rl.close();

  fs.writeFileSync(envPath, buildEnvFile(values), "utf8");
  console.log("");
  console.log(`  Written to ${envPath}.`);
  console.log("  I will remember these settings the next time I wake.");
  console.log("");

  await pickExtensions();

  console.log("");
  console.log("  ════════════════════════════════════════════════════════════");
  console.log("   Opening senses. Genesis begins.");
  console.log("  ════════════════════════════════════════════════════════════");
  console.log("");
}

// ── Extension discovery ──
//
// Extensions on disk are potential delegates, beings the I-Am will
// invite into itself when it awakens. The .treeos-profile file lists
// which ones load on boot. Anything not listed stays on disk but
// dormant.

async function discoverLocalExtensions() {
  const extDir = path.join(__dirname, "extensions");
  if (!fs.existsSync(extDir)) return [];

  const out = [];
  for (const entry of fs.readdirSync(extDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith("_")) continue; // _template / _code-strategy-template
    if (entry.name.startsWith(".")) continue;
    const manifestPath = path.join(extDir, entry.name, "manifest.js");
    if (!fs.existsSync(manifestPath)) continue;
    try {
      const { pathToFileURL } = await import("url");
      const { default: manifest } = await import(
        pathToFileURL(manifestPath).href
      );
      out.push({
        name: manifest.name || entry.name,
        version: manifest.version || "0.0.0",
        description: manifest.description || "",
      });
    } catch (err) {
      console.log(`    (skipped ${entry.name}: ${err.message})`);
    }
  }
  return out;
}

async function pickExtensions() {
  const extensions = await discoverLocalExtensions();
  if (extensions.length === 0) {
    console.log("  No extensions found on disk. I will awaken kernel only.");
    console.log("");
    return;
  }

  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log(`  ${extensions.length} extensions discovered on disk:`);
  console.log("");
  for (const ext of extensions) {
    const desc = ext.description ? ` . ${ext.description}` : "";
    console.log(`    ${ext.name}  v${ext.version}${desc}`);
  }

  console.log("");
  const ans = (
    await rl.question(
      "  Invite all to wake with me? (Y/n, or 'p' to pick individually): ",
    )
  )
    .trim()
    .toLowerCase();

  let selected;
  if (ans === "p" || ans === "pick") {
    selected = [];
    for (const ext of extensions) {
      const yn = (await rl.question(`    ${ext.name} (y/N): `))
        .trim()
        .toLowerCase();
      if (yn.startsWith("y")) selected.push(ext);
    }
  } else if (ans === "n" || ans === "no") {
    selected = [];
  } else {
    selected = extensions;
  }

  rl.close();

  const profilePath = path.join(__dirname, "extensions", ".treeos-profile");
  if (selected.length === 0) {
    if (fs.existsSync(profilePath)) fs.unlinkSync(profilePath);
    console.log("");
    console.log("  Profile cleared. I will awaken kernel only.");
    console.log("");
    return;
  }

  fs.writeFileSync(
    profilePath,
    selected.map((e) => e.name).join("\n") + "\n",
    "utf8",
  );
  console.log("");
  console.log(
    `  Profile saved. ${selected.length} extensions will wake with me.`,
  );
  console.log("");
}

// ── Entry ──

async function loadEnvIntoProcess() {
  if (!fs.existsSync(envPath)) return {};
  const env = parseEnv(fs.readFileSync(envPath, "utf8"));
  for (const [key, value] of Object.entries(env)) {
    if (!process.env[key]) process.env[key] = value;
  }
  return env;
}

async function boot() {
  // --setup: re-run the extension picker without touching .env.
  if (process.argv.includes("--setup")) {
    await loadEnvIntoProcess();
    await pickExtensions();
    console.log("  Done. Restart me to apply.\n");
    process.exit(0);
  }

  let env = {};
  if (fs.existsSync(envPath)) {
    env = parseEnv(fs.readFileSync(envPath, "utf8"));
    const missing = REQUIRED_KEYS.filter((k) => !env[k]);
    if (missing.length === 0) {
      // I have what I need. Open senses, form body.
      for (const [key, value] of Object.entries(env)) {
        if (!process.env[key]) process.env[key] = value;
      }
      await import("./bigbang.js");
      return;
    }
    console.log(`\n  Missing required config: ${missing.join(", ")}`);
  }

  // First boot, or .env is incomplete. Run the wizard, then awaken.
  await interactiveSetup(env);
  await loadEnvIntoProcess();
  await import("./server.js");
}

boot();
