// assetResolver.js . per-extension asset manifests + glTF/audio loaders.
//
// The portal stays substrate-blind. It doesn't know what extensions
// exist; it discovers them lazily by fetching `/assets/<ext>/manifest.json`
// the first time a `qualities.render.model` like "harmony:drum" needs
// resolving. The manifest endpoint is generated by the seed's loader
// from each extension's `provides.assets` block.
//
// Resolution paths:
//
//   model:   "harmony:drum" . assets.models["drum"]   . /assets/harmony/drum.glb
//   sound:   "harmony:hit"  . assets.sounds["hit"]    . /assets/harmony/drum-hit.mp3
//
// Caches:
//
//   _extensionManifests   . extName  . { models, sounds, ... } | null
//   _pendingManifestFetches . extName  . Promise (de-dupes concurrent fetches)
//   _loadedModels         . URL   . THREE.Group (the loaded glTF scene)
//   _pendingModelLoads    . URL   . Promise (de-dupes concurrent loads)
//
// loadModel() returns a CLONE of the cached scene so callers can
// position/scale independently without touching the shared cache.
// Geometry and materials stay shared across clones (no extra GPU
// upload).

import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { DRACOLoader } from "three/examples/jsm/loaders/DRACOLoader.js";
import { clone as cloneSkinned } from "three/examples/jsm/utils/SkeletonUtils.js";

// Wire DRACOLoader so glTFs compressed with Draco mesh compression
// (the standard size-reduction step for Mixamo characters, Sketchfab
// downloads, etc.) decompress on load. The decoder WASM lives on
// gstatic so we don't bundle ~100 KB of decoder bytes into every
// portal build.
const _gltfLoader = new GLTFLoader();
const _dracoLoader = new DRACOLoader();
_dracoLoader.setDecoderPath("https://www.gstatic.com/draco/v1/decoders/");
_gltfLoader.setDRACOLoader(_dracoLoader);

const _extensionManifests = new Map();
const _pendingManifestFetches = new Map();
const _loadedModels = new Map();
const _pendingModelLoads = new Map();

/**
 * Split a qualified asset id like "harmony:drum" into its parts.
 * Returns null for malformed inputs.
 */
export function parseAssetId(id) {
  if (typeof id !== "string" || !id) return null;
  const colon = id.indexOf(":");
  if (colon <= 0 || colon === id.length - 1) return null;
  const ext = id.slice(0, colon);
  const name = id.slice(colon + 1);
  if (!ext || !name) return null;
  return { ext, name };
}

/**
 * Fetch (and cache) an extension's asset manifest. Returns null when
 * the manifest is missing or malformed.
 */
export async function getExtensionManifest(extName) {
  if (!extName) return null;
  if (_extensionManifests.has(extName)) return _extensionManifests.get(extName);
  if (_pendingManifestFetches.has(extName)) return _pendingManifestFetches.get(extName);

  const promise = (async () => {
    try {
      const res = await fetch(`/assets/${extName}/manifest.json`);
      if (!res.ok) return null;
      const json = await res.json();
      if (!json || typeof json !== "object") return null;
      return json;
    } catch {
      return null;
    }
  })().then((result) => {
    _extensionManifests.set(extName, result);
    _pendingManifestFetches.delete(extName);
    return result;
  });

  _pendingManifestFetches.set(extName, promise);
  return promise;
}

/**
 * Resolve a model reference to its URL. Three shapes:
 *
 *   "ext:name"            — extension asset; resolved via the
 *                           extension's /assets manifest (legacy).
 *   "/api/v1/content/..." — direct URL (any "/..." or "http..."
 *                           string passes through).
 *   { url, hash, ... }    — a model MATTER block (set-model writes
 *                           these; bytes live in the content store,
 *                           served immutable by hash).
 *
 * Returns null when unresolvable.
 */
export async function resolveModelUrl(modelRef) {
  if (modelRef && typeof modelRef === "object") {
    return typeof modelRef.url === "string" && modelRef.url ? modelRef.url : null;
  }
  if (typeof modelRef !== "string" || !modelRef) return null;
  if (modelRef.startsWith("/") || modelRef.startsWith("http")) return modelRef;
  const parsed = parseAssetId(modelRef);
  if (!parsed) return null;
  const manifest = await getExtensionManifest(parsed.ext);
  const filename = manifest?.models?.[parsed.name];
  if (!filename || typeof filename !== "string") return null;
  return `/assets/${parsed.ext}/${filename}`;
}

/**
 * Same shape for sounds. Used by rung 3's Web Audio renderer.
 */
export async function resolveSoundUrl(soundId) {
  const parsed = parseAssetId(soundId);
  if (!parsed) return null;
  const manifest = await getExtensionManifest(parsed.ext);
  const filename = manifest?.sounds?.[parsed.name];
  if (!filename || typeof filename !== "string") return null;
  return `/assets/${parsed.ext}/${filename}`;
}

/**
 * Load a glTF model. Returns `{ scene, animations }` where:
 *   - `scene` is a fresh deep clone of the gltf's root scene (skinned
 *     meshes are cloned via SkeletonUtils so the new clone gets its
 *     own Skeleton bound to the cloned bone hierarchy . a plain
 *     scene.clone() would bind the new SkinnedMesh to the original's
 *     bones and rung-3 AnimationMixer drives wouldn't reach the
 *     cloned mesh).
 *   - `animations` is the gltf.animations array (THREE.AnimationClip[]).
 *     SAFE TO SHARE across clones . each AnimationMixer creates its
 *     own AnimationAction per (mesh, clip) pair, so the clip data
 *     itself is read-only at runtime.
 *
 * The underlying loaded gltf is cached by URL; subsequent calls clone
 * the cached scene and return the same animations reference.
 *
 * Returns null on missing-asset / network / parse failures; callers
 * fall back to their primitive placeholder.
 */
export async function loadModel(modelId) {
  const url = await resolveModelUrl(modelId);
  if (!url) return null;

  if (_loadedModels.has(url)) {
    const cached = _loadedModels.get(url);
    return { scene: cloneSkinned(cached.scene), animations: cached.animations };
  }
  if (_pendingModelLoads.has(url)) {
    const cached = await _pendingModelLoads.get(url);
    return cached ? { scene: cloneSkinned(cached.scene), animations: cached.animations } : null;
  }

  const promise = new Promise((resolve) => {
    _gltfLoader.load(
      url,
      (gltf) => {
        if (!gltf?.scene) return resolve(null);
        // Strip root motion from every animation clip before caching.
        // Mixamo + similar pipelines bake hip translation into the clip
        // tracks, which makes the character walk away from its
        // substrate-defined position when the clip plays . the bone
        // moves through the rig while the outer mesh stays put. The
        // grid-cell scene needs characters anchored, so we drop the
        // root-bone position track and let the rest of the rig animate
        // legs/arms/torso in place. Done once at load time; the
        // mutation is on the shared cached clip so every clone of this
        // glTF gets the de-motioned version.
        const animations = Array.isArray(gltf.animations) ? gltf.animations : [];
        for (const clip of animations) _stripRootMotion(clip);
        resolve({ scene: gltf.scene, animations });
      },
      undefined,
      (err) => {
        console.warn(`[assetResolver] glTF load failed for ${url}:`, err?.message || err);
        resolve(null);
      },
    );
  }).then((cached) => {
    if (cached) _loadedModels.set(url, cached);
    _pendingModelLoads.delete(url);
    return cached;
  });

  _pendingModelLoads.set(url, promise);
  const cached = await promise;
  return cached ? { scene: cloneSkinned(cached.scene), animations: cached.animations } : null;
}

// Files larger than this are skipped from the preload pass entirely.
// They lazy-load on-demand through the existing swap-on-load path the
// first time a scene asks for them. The threshold is a guard against
// one oversized asset starving the rest of the preload window.
const SIZE_SKIP_THRESHOLD = 20 * 1024 * 1024;

async function fetchSizeOrNull(url) {
  try {
    const res = await fetch(url, { method: "HEAD" });
    if (!res.ok) return null;
    const len = res.headers.get("content-length");
    return len ? Number(len) : null;
  } catch {
    return null;
  }
}

/**
 * Fire every model load in parallel; resolve when all settle OR the
 * timeout elapses. Used by the first-load / replay-start path so the
 * scene paints with loaded glTFs in one frame rather than a sea of
 * placeholder primitives that swap in piecemeal.
 *
 * Models larger than SIZE_SKIP_THRESHOLD are skipped here and lazy-load
 * on-demand via loadModel() the first time the scene asks. A single
 * oversized file shouldn't block the whole preload pass.
 *
 * Returns void; check loadModel(modelId) afterwards to retrieve
 * results (each one has been cached during preload).
 */
export async function preloadModels(modelIds, { timeoutMs = 3000 } = {}) {
  if (!Array.isArray(modelIds) || modelIds.length === 0) return;
  const unique = Array.from(new Set(modelIds.filter(Boolean)));
  if (unique.length === 0) return;

  const sized = await Promise.all(unique.map(async (id) => {
    const url = await resolveModelUrl(id);
    if (!url) return { id, skip: true };
    const size = await fetchSizeOrNull(url);
    return { id, url, size, skip: size && size > SIZE_SKIP_THRESHOLD };
  }));

  const skipped = sized.filter((s) => s.skip && s.size);
  for (const s of skipped) {
    const label = typeof s.id === "string" ? s.id : (s.url || s.id?.url || "model");
    console.warn(
      `[assetResolver] preload skipping ${label} (${(s.size / 1024 / 1024).toFixed(1)} MB > 20 MB threshold); will lazy-load on demand`,
    );
  }

  const loads = sized
    .filter((s) => !s.skip)
    .map((s) => loadModel(s.id).catch(() => null));
  const all = Promise.allSettled(loads);
  const timeout = new Promise((resolve) => setTimeout(resolve, timeoutMs));
  await Promise.race([all, timeout]);
}

// ────────────────────────────────────────────────────────────────────
// Root-motion stripping. Mixamo (and similar FBX-derived pipelines)
// bake hip translation into the clip's tracks: a "Walking" clip stamps
// position keyframes on `mixamorigHips` that move the character a
// meter or so per loop. In a grid-cell scene that uses substrate
// coords as the source of truth, this reads as "the dancer steps,
// reaches the new cell, then their dance clip drifts them further off."
// Stripping the position track on the hip / root bone keeps the bone
// at its bind-pose position while rotation tracks still animate every
// other bone. Net: legs walk, arms swing, character stays where the
// substrate puts them.
//
// Variants we handle. Different glTF converters / Blender exports write
// the same character hip with different track names. We match on a
// liberal list of root-bone tokens and require the track to be a
// `.position` track (rotation/scale tracks are kept).
//   . mixamorigHips                  bare prefix, no separator
//   . mixamorig:Hips                 prefix + colon
//   . mixamorig_Hips                 prefix + underscore
//   . Hips                            prefix stripped at export
//   . Armature / RootNode             root carries the translation
//   . root                            generic root bone
// Anything else with `.position` (eyes, fingers, prop bones) passes
// through, since stripping those would break legitimate detail anim.
// ────────────────────────────────────────────────────────────────────
const _ROOT_BONE_RE = /(^|[/.|])(mixamorig[:_]?Hips|Hips|Armature|RootNode|root)\.position(\.|$|\[)/i;

function _stripRootMotion(clip) {
  if (!clip || !Array.isArray(clip.tracks)) return clip;
  const removed = [];
  const kept = [];
  clip.tracks = clip.tracks.filter((track) => {
    if (!track || typeof track.name !== "string") return true;
    if (_ROOT_BONE_RE.test(track.name)) {
      removed.push(track.name);
      return false;
    }
    if (track.name.endsWith(".position")) kept.push(track.name);
    return true;
  });
  if (removed.length > 0) {
    console.log(
      `[assetResolver] stripped root motion from clip "${clip.name}" . removed:`,
      removed,
    );
  } else if (kept.length > 0) {
    // Diagnostic: clip has position tracks we DIDN'T strip. If the
    // character still drifts during this clip, the root bone has a
    // name the regex didn't match . widen _ROOT_BONE_RE to include it.
    console.warn(
      `[assetResolver] clip "${clip.name}" has position tracks the root-motion ` +
        `stripper did NOT match; if it drifts, widen the regex to include one of:`,
      kept,
    );
  }
  return clip;
}

/**
 * Walk a descriptor and collect every sound id declared on a render
 * block. Mirrors collectModelIds. Used by the first-load preload
 * pass so the audio player has decoded AudioBuffers ready when the
 * first fact arrives.
 */
export function collectSoundIds(desc) {
  if (!desc || typeof desc !== "object") return [];
  const out = new Set();
  const walk = (entry) => {
    const sounds = entry?.qualities?.render?.sounds;
    if (sounds && typeof sounds === "object") {
      for (const v of Object.values(sounds)) {
        if (typeof v === "string" && v) out.add(v);
      }
    }
  };
  (desc.beings || []).forEach(walk);
  (desc.matter || []).forEach(walk);
  (desc.children || []).forEach(walk);
  return [...out];
}

/**
 * Walk a descriptor and collect every model reference declared on a
 * render block or on the resolved `model` field (beings / children /
 * matter entries carry it server-resolved). String refs dedupe by
 * value; object refs (model matter blocks) dedupe by url. Used by
 * the first-load preload pass; preloadModels resolves each through
 * resolveModelUrl, so both shapes flow.
 */
export function collectModelIds(desc) {
  if (!desc || typeof desc !== "object") return [];
  const out = new Map(); // key → ref
  const add = (ref) => {
    if (typeof ref === "string" && ref) out.set(ref, ref);
    else if (ref && typeof ref === "object" && typeof ref.url === "string") out.set(ref.url, ref);
  };
  const walk = (entry) => {
    add(entry?.qualities?.render?.model);
    add(entry?.model);
  };
  (desc.beings || []).forEach(walk);
  (desc.residents || []).forEach(walk);
  (desc.matter || []).forEach(walk);
  (desc.matters || []).forEach(walk);
  (desc.children || []).forEach(walk);
  return [...out.values()];
}
